//go:build integration

package database_test

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"testing"
	"time"

	"github.com/Easy-Bao/DrivingApp/server/internal/platform/database/migrations"
	databasepostgres "github.com/Easy-Bao/DrivingApp/server/internal/platform/database/postgres"
	"github.com/jackc/pgx/v5"
)

func TestWalletLedgerSupportsSecondaryEntriesAndIdempotency(t *testing.T) {
	databaseURL := os.Getenv("TEST_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("TEST_DATABASE_URL is not set")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	admin, err := pgx.Connect(ctx, databaseURL)
	if err != nil {
		t.Fatalf("connect to test PostgreSQL database: %v", err)
	}

	schemaName := fmt.Sprintf("wallet_ledger_it_%d", time.Now().UnixNano())
	quotedSchema := pgx.Identifier{schemaName}.Sanitize()
	if _, err := admin.Exec(ctx, "CREATE SCHEMA "+quotedSchema); err != nil {
		_ = admin.Close(context.Background())
		t.Fatalf("create isolated test schema: %v", err)
	}

	var connection *pgx.Conn
	t.Cleanup(func() {
		cleanupContext, cleanupCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cleanupCancel()
		if connection != nil {
			_ = connection.Close(cleanupContext)
		}
		_, _ = admin.Exec(cleanupContext, "DROP SCHEMA "+quotedSchema+" CASCADE")
		_ = admin.Close(cleanupContext)
	})

	config, err := pgx.ParseConfig(databaseURL)
	if err != nil {
		t.Fatalf("parse test PostgreSQL connection: %v", err)
	}
	config.RuntimeParams["search_path"] = schemaName
	connection, err = pgx.ConnectConfig(ctx, config)
	if err != nil {
		t.Fatalf("connect to isolated test schema: %v", err)
	}

	_, err = connection.Exec(ctx, `
CREATE TABLE wallet_ledgers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id integer NOT NULL,
    ride_id integer NOT NULL,
    amount bigint NOT NULL,
    commission_amount bigint NOT NULL,
    kind text NOT NULL DEFAULT 'cash_trip',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
)`)
	if err != nil {
		t.Fatalf("create pre-migration wallet ledger: %v", err)
	}
	if _, err := connection.Exec(ctx, `
INSERT INTO wallet_ledgers (driver_id, ride_id, amount, commission_amount)
VALUES (11, 42, 1200, 100)`); err != nil {
		t.Fatalf("seed legacy ledger row: %v", err)
	}
	if _, err := connection.Exec(ctx, "CREATE UNIQUE INDEX walletledger_ride_id ON wallet_ledgers (ride_id)"); err != nil {
		t.Fatalf("create legacy per-ride index: %v", err)
	}
	for _, migrationName := range []string{
		"2026100901_wallet_ledger_idempotency.up.sql",
		"2026100902_wallet_ledger_idempotency_index.up.sql",
		"2026100903_wallet_ledger_ride_kind_index.up.sql",
		"2026100904_wallet_ledger_multi_entry.up.sql",
	} {
		if err := executeEmbeddedMigration(ctx, connection, migrationName); err != nil {
			t.Fatalf("apply %s: %v", migrationName, err)
		}
	}

	var oldRideIndexExists bool
	if err := connection.QueryRow(ctx, `
SELECT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = current_schema()
      AND indexname = 'walletledger_ride_id'
)`).Scan(&oldRideIndexExists); err != nil {
		t.Fatalf("check old per-ride index: %v", err)
	}
	if oldRideIndexExists {
		t.Fatal("old per-ride unique index still exists after migration")
	}
	var legacyKeyIsNull bool
	if err := connection.QueryRow(ctx, `
SELECT idempotency_key IS NULL
FROM wallet_ledgers
WHERE ride_id = 42 AND kind = 'cash_trip'`).Scan(&legacyKeyIsNull); err != nil {
		t.Fatalf("check legacy idempotency key: %v", err)
	}
	if !legacyKeyIsNull {
		t.Fatal("legacy ledger row unexpectedly received an idempotency key")
	}
	if _, err := connection.Exec(ctx, `
INSERT INTO wallet_ledgers (driver_id, ride_id, amount, commission_amount, kind)
VALUES (11, 44, 100, 0, 'platform_fee')`); err != nil {
		t.Fatalf("insert with idempotency-key default: %v", err)
	}
	var defaultKeyIsPresent bool
	if err := connection.QueryRow(ctx, `
SELECT idempotency_key IS NOT NULL
FROM wallet_ledgers
WHERE ride_id = 44 AND kind = 'platform_fee'`).Scan(&defaultKeyIsPresent); err != nil {
		t.Fatalf("check default idempotency key: %v", err)
	}
	if !defaultKeyIsPresent {
		t.Fatal("new ledger row did not receive a default idempotency key")
	}
	if _, err := connection.Exec(ctx, `
INSERT INTO wallet_ledgers (driver_id, ride_id, amount, commission_amount, kind, idempotency_key)
VALUES (11, 45, 100, 0, 'fare_adjustment', NULL)`); err == nil {
		t.Fatal("migration accepted a new ledger row without an idempotency key")
	}

	queries := databasepostgres.New(connection)
	entries := []databasepostgres.CreateWalletLedgerParams{
		{DriverID: 11, RideID: 42, Amount: 300, CommissionAmount: 0, Kind: "passenger_tip", IdempotencyKey: "ride:42:tip:1"},
		{DriverID: 11, RideID: 42, Amount: 150, CommissionAmount: 0, Kind: "toll_reimbursement", IdempotencyKey: "ride:42:toll:1"},
		{DriverID: 11, RideID: 42, Amount: -200, CommissionAmount: 0, Kind: "fare_adjustment", IdempotencyKey: "ride:42:adjustment:1"},
	}
	for _, entry := range entries {
		inserted, err := queries.CreateWalletLedger(ctx, entry)
		if err != nil {
			t.Fatalf("insert %s ledger entry: %v", entry.Kind, err)
		}
		if inserted != 1 {
			t.Fatalf("inserted %s rows = %d, want 1", entry.Kind, inserted)
		}
	}

	duplicate := entries[0]
	duplicate.RideID = 43
	inserted, err := queries.CreateWalletLedger(ctx, duplicate)
	if err != nil {
		t.Fatalf("retry duplicate idempotency key: %v", err)
	}
	if inserted != 0 {
		t.Fatalf("duplicate idempotency key inserted %d rows, want 0", inserted)
	}

	var rideEntryCount int
	if err := connection.QueryRow(ctx, "SELECT count(*) FROM wallet_ledgers WHERE ride_id = 42").Scan(&rideEntryCount); err != nil {
		t.Fatalf("count ride ledger entries: %v", err)
	}
	if rideEntryCount != 4 {
		t.Fatalf("ride ledger entry count = %d, want 4", rideEntryCount)
	}

	if err := executeEmbeddedMigration(ctx, connection, "2026100904_wallet_ledger_multi_entry.down.sql"); err != nil {
	}
	if err := connection.QueryRow(ctx, "SELECT count(*) FROM wallet_ledgers WHERE ride_id = 42").Scan(&rideEntryCount); err != nil {
		t.Fatalf("count ride ledger entries after rollback: %v", err)
	}
	if rideEntryCount != 4 {
		t.Fatalf("rollback retained %d ride ledger entries, want 4", rideEntryCount)
	}
	if err := connection.QueryRow(ctx, `
SELECT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = current_schema()
      AND indexname = 'walletledger_ride_id'
)`).Scan(&oldRideIndexExists); err != nil {
		t.Fatalf("check old per-ride index after rollback: %v", err)
	}
	if oldRideIndexExists {
		t.Fatal("rollback introduced an index absent from the active migration history")
	}
}

func executeEmbeddedMigration(ctx context.Context, connection *pgx.Conn, name string) error {
	sql, err := fs.ReadFile(migrations.FS, name)
	if err != nil {
		return fmt.Errorf("read migration: %w", err)
	}
	_, err = connection.PgConn().Exec(ctx, string(sql)).ReadAll()
	return err
}
