// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/bid"
)

// BidCreate is the builder for creating a Bid entity.
type BidCreate struct {
	config
	mutation *BidMutation
	hooks    []Hook
}

// SetRideID sets the "ride_id" field.
func (_c *BidCreate) SetRideID(v int) *BidCreate {
	_c.mutation.SetRideID(v)
	return _c
}

// SetDriverID sets the "driver_id" field.
func (_c *BidCreate) SetDriverID(v int) *BidCreate {
	_c.mutation.SetDriverID(v)
	return _c
}

// SetOfferedFareCentavos sets the "offered_fare_centavos" field.
func (_c *BidCreate) SetOfferedFareCentavos(v int64) *BidCreate {
	_c.mutation.SetOfferedFareCentavos(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *BidCreate) SetStatus(v string) *BidCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BidCreate) SetNillableStatus(v *string) *BidCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// Mutation returns the BidMutation object of the builder.
func (_c *BidCreate) Mutation() *BidMutation {
	return _c.mutation
}

// Save creates the Bid in the database.
func (_c *BidCreate) Save(ctx context.Context) (*Bid, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BidCreate) SaveX(ctx context.Context) *Bid {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BidCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BidCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BidCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := bid.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BidCreate) check() error {
	if _, ok := _c.mutation.RideID(); !ok {
		return &ValidationError{Name: "ride_id", err: errors.New(`ent: missing required field "Bid.ride_id"`)}
	}
	if v, ok := _c.mutation.RideID(); ok {
		if err := bid.RideIDValidator(v); err != nil {
			return &ValidationError{Name: "ride_id", err: fmt.Errorf(`ent: validator failed for field "Bid.ride_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DriverID(); !ok {
		return &ValidationError{Name: "driver_id", err: errors.New(`ent: missing required field "Bid.driver_id"`)}
	}
	if v, ok := _c.mutation.DriverID(); ok {
		if err := bid.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "Bid.driver_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OfferedFareCentavos(); !ok {
		return &ValidationError{Name: "offered_fare_centavos", err: errors.New(`ent: missing required field "Bid.offered_fare_centavos"`)}
	}
	if v, ok := _c.mutation.OfferedFareCentavos(); ok {
		if err := bid.OfferedFareCentavosValidator(v); err != nil {
			return &ValidationError{Name: "offered_fare_centavos", err: fmt.Errorf(`ent: validator failed for field "Bid.offered_fare_centavos": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Bid.status"`)}
	}
	return nil
}

func (_c *BidCreate) sqlSave(ctx context.Context) (*Bid, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BidCreate) createSpec() (*Bid, *sqlgraph.CreateSpec) {
	var (
		_node = &Bid{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bid.Table, sqlgraph.NewFieldSpec(bid.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RideID(); ok {
		_spec.SetField(bid.FieldRideID, field.TypeInt, value)
		_node.RideID = value
	}
	if value, ok := _c.mutation.DriverID(); ok {
		_spec.SetField(bid.FieldDriverID, field.TypeInt, value)
		_node.DriverID = value
	}
	if value, ok := _c.mutation.OfferedFareCentavos(); ok {
		_spec.SetField(bid.FieldOfferedFareCentavos, field.TypeInt64, value)
		_node.OfferedFareCentavos = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bid.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// BidCreateBulk is the builder for creating many Bid entities in bulk.
type BidCreateBulk struct {
	config
	err      error
	builders []*BidCreate
}

// Save creates the Bid entities in the database.
func (_c *BidCreateBulk) Save(ctx context.Context) ([]*Bid, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Bid, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BidMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BidCreateBulk) SaveX(ctx context.Context) []*Bid {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BidCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BidCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
