// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/bidsession"
	"github.com/Easy-Bao/DrivingApp/server/ent/predicate"
)

// BidSessionUpdate is the builder for updating BidSession entities.
type BidSessionUpdate struct {
	config
	hooks    []Hook
	mutation *BidSessionMutation
}

// Where appends a list predicates to the BidSessionUpdate builder.
func (_u *BidSessionUpdate) Where(ps ...predicate.BidSession) *BidSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPassengerID sets the "passenger_id" field.
func (_u *BidSessionUpdate) SetPassengerID(v int) *BidSessionUpdate {
	_u.mutation.ResetPassengerID()
	_u.mutation.SetPassengerID(v)
	return _u
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillablePassengerID(v *int) *BidSessionUpdate {
	if v != nil {
		_u.SetPassengerID(*v)
	}
	return _u
}

// AddPassengerID adds value to the "passenger_id" field.
func (_u *BidSessionUpdate) AddPassengerID(v int) *BidSessionUpdate {
	_u.mutation.AddPassengerID(v)
	return _u
}

// SetRideType sets the "ride_type" field.
func (_u *BidSessionUpdate) SetRideType(v string) *BidSessionUpdate {
	_u.mutation.SetRideType(v)
	return _u
}

// SetNillableRideType sets the "ride_type" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableRideType(v *string) *BidSessionUpdate {
	if v != nil {
		_u.SetRideType(*v)
	}
	return _u
}

// SetPickupLatitude sets the "pickup_latitude" field.
func (_u *BidSessionUpdate) SetPickupLatitude(v float64) *BidSessionUpdate {
	_u.mutation.ResetPickupLatitude()
	_u.mutation.SetPickupLatitude(v)
	return _u
}

// SetNillablePickupLatitude sets the "pickup_latitude" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillablePickupLatitude(v *float64) *BidSessionUpdate {
	if v != nil {
		_u.SetPickupLatitude(*v)
	}
	return _u
}

// AddPickupLatitude adds value to the "pickup_latitude" field.
func (_u *BidSessionUpdate) AddPickupLatitude(v float64) *BidSessionUpdate {
	_u.mutation.AddPickupLatitude(v)
	return _u
}

// SetPickupLongitude sets the "pickup_longitude" field.
func (_u *BidSessionUpdate) SetPickupLongitude(v float64) *BidSessionUpdate {
	_u.mutation.ResetPickupLongitude()
	_u.mutation.SetPickupLongitude(v)
	return _u
}

// SetNillablePickupLongitude sets the "pickup_longitude" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillablePickupLongitude(v *float64) *BidSessionUpdate {
	if v != nil {
		_u.SetPickupLongitude(*v)
	}
	return _u
}

// AddPickupLongitude adds value to the "pickup_longitude" field.
func (_u *BidSessionUpdate) AddPickupLongitude(v float64) *BidSessionUpdate {
	_u.mutation.AddPickupLongitude(v)
	return _u
}

// SetPickupName sets the "pickup_name" field.
func (_u *BidSessionUpdate) SetPickupName(v string) *BidSessionUpdate {
	_u.mutation.SetPickupName(v)
	return _u
}

// SetNillablePickupName sets the "pickup_name" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillablePickupName(v *string) *BidSessionUpdate {
	if v != nil {
		_u.SetPickupName(*v)
	}
	return _u
}

// SetDropoffLatitude sets the "dropoff_latitude" field.
func (_u *BidSessionUpdate) SetDropoffLatitude(v float64) *BidSessionUpdate {
	_u.mutation.ResetDropoffLatitude()
	_u.mutation.SetDropoffLatitude(v)
	return _u
}

// SetNillableDropoffLatitude sets the "dropoff_latitude" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableDropoffLatitude(v *float64) *BidSessionUpdate {
	if v != nil {
		_u.SetDropoffLatitude(*v)
	}
	return _u
}

// AddDropoffLatitude adds value to the "dropoff_latitude" field.
func (_u *BidSessionUpdate) AddDropoffLatitude(v float64) *BidSessionUpdate {
	_u.mutation.AddDropoffLatitude(v)
	return _u
}

// SetDropoffLongitude sets the "dropoff_longitude" field.
func (_u *BidSessionUpdate) SetDropoffLongitude(v float64) *BidSessionUpdate {
	_u.mutation.ResetDropoffLongitude()
	_u.mutation.SetDropoffLongitude(v)
	return _u
}

// SetNillableDropoffLongitude sets the "dropoff_longitude" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableDropoffLongitude(v *float64) *BidSessionUpdate {
	if v != nil {
		_u.SetDropoffLongitude(*v)
	}
	return _u
}

// AddDropoffLongitude adds value to the "dropoff_longitude" field.
func (_u *BidSessionUpdate) AddDropoffLongitude(v float64) *BidSessionUpdate {
	_u.mutation.AddDropoffLongitude(v)
	return _u
}

// SetDropoffName sets the "dropoff_name" field.
func (_u *BidSessionUpdate) SetDropoffName(v string) *BidSessionUpdate {
	_u.mutation.SetDropoffName(v)
	return _u
}

// SetNillableDropoffName sets the "dropoff_name" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableDropoffName(v *string) *BidSessionUpdate {
	if v != nil {
		_u.SetDropoffName(*v)
	}
	return _u
}

// SetPassengerNote sets the "passenger_note" field.
func (_u *BidSessionUpdate) SetPassengerNote(v string) *BidSessionUpdate {
	_u.mutation.SetPassengerNote(v)
	return _u
}

// SetNillablePassengerNote sets the "passenger_note" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillablePassengerNote(v *string) *BidSessionUpdate {
	if v != nil {
		_u.SetPassengerNote(*v)
	}
	return _u
}

// ClearPassengerNote clears the value of the "passenger_note" field.
func (_u *BidSessionUpdate) ClearPassengerNote() *BidSessionUpdate {
	_u.mutation.ClearPassengerNote()
	return _u
}

// SetDistanceKm sets the "distance_km" field.
func (_u *BidSessionUpdate) SetDistanceKm(v float64) *BidSessionUpdate {
	_u.mutation.ResetDistanceKm()
	_u.mutation.SetDistanceKm(v)
	return _u
}

// SetNillableDistanceKm sets the "distance_km" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableDistanceKm(v *float64) *BidSessionUpdate {
	if v != nil {
		_u.SetDistanceKm(*v)
	}
	return _u
}

// AddDistanceKm adds value to the "distance_km" field.
func (_u *BidSessionUpdate) AddDistanceKm(v float64) *BidSessionUpdate {
	_u.mutation.AddDistanceKm(v)
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *BidSessionUpdate) SetDurationMinutes(v float64) *BidSessionUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableDurationMinutes(v *float64) *BidSessionUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *BidSessionUpdate) AddDurationMinutes(v float64) *BidSessionUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetOfferedFareCentavos sets the "offered_fare_centavos" field.
func (_u *BidSessionUpdate) SetOfferedFareCentavos(v int64) *BidSessionUpdate {
	_u.mutation.ResetOfferedFareCentavos()
	_u.mutation.SetOfferedFareCentavos(v)
	return _u
}

// SetNillableOfferedFareCentavos sets the "offered_fare_centavos" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableOfferedFareCentavos(v *int64) *BidSessionUpdate {
	if v != nil {
		_u.SetOfferedFareCentavos(*v)
	}
	return _u
}

// AddOfferedFareCentavos adds value to the "offered_fare_centavos" field.
func (_u *BidSessionUpdate) AddOfferedFareCentavos(v int64) *BidSessionUpdate {
	_u.mutation.AddOfferedFareCentavos(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BidSessionUpdate) SetStatus(v string) *BidSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableStatus(v *string) *BidSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTargetDriverID sets the "target_driver_id" field.
func (_u *BidSessionUpdate) SetTargetDriverID(v int) *BidSessionUpdate {
	_u.mutation.ResetTargetDriverID()
	_u.mutation.SetTargetDriverID(v)
	return _u
}

// SetNillableTargetDriverID sets the "target_driver_id" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableTargetDriverID(v *int) *BidSessionUpdate {
	if v != nil {
		_u.SetTargetDriverID(*v)
	}
	return _u
}

// AddTargetDriverID adds value to the "target_driver_id" field.
func (_u *BidSessionUpdate) AddTargetDriverID(v int) *BidSessionUpdate {
	_u.mutation.AddTargetDriverID(v)
	return _u
}

// ClearTargetDriverID clears the value of the "target_driver_id" field.
func (_u *BidSessionUpdate) ClearTargetDriverID() *BidSessionUpdate {
	_u.mutation.ClearTargetDriverID()
	return _u
}

// SetAcceptedDriverID sets the "accepted_driver_id" field.
func (_u *BidSessionUpdate) SetAcceptedDriverID(v int) *BidSessionUpdate {
	_u.mutation.ResetAcceptedDriverID()
	_u.mutation.SetAcceptedDriverID(v)
	return _u
}

// SetNillableAcceptedDriverID sets the "accepted_driver_id" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableAcceptedDriverID(v *int) *BidSessionUpdate {
	if v != nil {
		_u.SetAcceptedDriverID(*v)
	}
	return _u
}

// AddAcceptedDriverID adds value to the "accepted_driver_id" field.
func (_u *BidSessionUpdate) AddAcceptedDriverID(v int) *BidSessionUpdate {
	_u.mutation.AddAcceptedDriverID(v)
	return _u
}

// ClearAcceptedDriverID clears the value of the "accepted_driver_id" field.
func (_u *BidSessionUpdate) ClearAcceptedDriverID() *BidSessionUpdate {
	_u.mutation.ClearAcceptedDriverID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BidSessionUpdate) SetExpiresAt(v time.Time) *BidSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableExpiresAt(v *time.Time) *BidSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BidSessionUpdate) SetCreatedAt(v time.Time) *BidSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BidSessionUpdate) SetNillableCreatedAt(v *time.Time) *BidSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the BidSessionMutation object of the builder.
func (_u *BidSessionUpdate) Mutation() *BidSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BidSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BidSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BidSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BidSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BidSessionUpdate) check() error {
	if v, ok := _u.mutation.PassengerID(); ok {
		if err := bidsession.PassengerIDValidator(v); err != nil {
			return &ValidationError{Name: "passenger_id", err: fmt.Errorf(`ent: validator failed for field "BidSession.passenger_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PassengerNote(); ok {
		if err := bidsession.PassengerNoteValidator(v); err != nil {
			return &ValidationError{Name: "passenger_note", err: fmt.Errorf(`ent: validator failed for field "BidSession.passenger_note": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OfferedFareCentavos(); ok {
		if err := bidsession.OfferedFareCentavosValidator(v); err != nil {
			return &ValidationError{Name: "offered_fare_centavos", err: fmt.Errorf(`ent: validator failed for field "BidSession.offered_fare_centavos": %w`, err)}
		}
	}
	return nil
}

func (_u *BidSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bidsession.Table, bidsession.Columns, sqlgraph.NewFieldSpec(bidsession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PassengerID(); ok {
		_spec.SetField(bidsession.FieldPassengerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassengerID(); ok {
		_spec.AddField(bidsession.FieldPassengerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RideType(); ok {
		_spec.SetField(bidsession.FieldRideType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickupLatitude(); ok {
		_spec.SetField(bidsession.FieldPickupLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPickupLatitude(); ok {
		_spec.AddField(bidsession.FieldPickupLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PickupLongitude(); ok {
		_spec.SetField(bidsession.FieldPickupLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPickupLongitude(); ok {
		_spec.AddField(bidsession.FieldPickupLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PickupName(); ok {
		_spec.SetField(bidsession.FieldPickupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DropoffLatitude(); ok {
		_spec.SetField(bidsession.FieldDropoffLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDropoffLatitude(); ok {
		_spec.AddField(bidsession.FieldDropoffLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DropoffLongitude(); ok {
		_spec.SetField(bidsession.FieldDropoffLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDropoffLongitude(); ok {
		_spec.AddField(bidsession.FieldDropoffLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DropoffName(); ok {
		_spec.SetField(bidsession.FieldDropoffName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassengerNote(); ok {
		_spec.SetField(bidsession.FieldPassengerNote, field.TypeString, value)
	}
	if _u.mutation.PassengerNoteCleared() {
		_spec.ClearField(bidsession.FieldPassengerNote, field.TypeString)
	}
	if value, ok := _u.mutation.DistanceKm(); ok {
		_spec.SetField(bidsession.FieldDistanceKm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDistanceKm(); ok {
		_spec.AddField(bidsession.FieldDistanceKm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(bidsession.FieldDurationMinutes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(bidsession.FieldDurationMinutes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OfferedFareCentavos(); ok {
		_spec.SetField(bidsession.FieldOfferedFareCentavos, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOfferedFareCentavos(); ok {
		_spec.AddField(bidsession.FieldOfferedFareCentavos, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bidsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDriverID(); ok {
		_spec.SetField(bidsession.FieldTargetDriverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetDriverID(); ok {
		_spec.AddField(bidsession.FieldTargetDriverID, field.TypeInt, value)
	}
	if _u.mutation.TargetDriverIDCleared() {
		_spec.ClearField(bidsession.FieldTargetDriverID, field.TypeInt)
	}
	if value, ok := _u.mutation.AcceptedDriverID(); ok {
		_spec.SetField(bidsession.FieldAcceptedDriverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAcceptedDriverID(); ok {
		_spec.AddField(bidsession.FieldAcceptedDriverID, field.TypeInt, value)
	}
	if _u.mutation.AcceptedDriverIDCleared() {
		_spec.ClearField(bidsession.FieldAcceptedDriverID, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bidsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bidsession.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bidsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BidSessionUpdateOne is the builder for updating a single BidSession entity.
type BidSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BidSessionMutation
}

// SetPassengerID sets the "passenger_id" field.
func (_u *BidSessionUpdateOne) SetPassengerID(v int) *BidSessionUpdateOne {
	_u.mutation.ResetPassengerID()
	_u.mutation.SetPassengerID(v)
	return _u
}

// SetNillablePassengerID sets the "passenger_id" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillablePassengerID(v *int) *BidSessionUpdateOne {
	if v != nil {
		_u.SetPassengerID(*v)
	}
	return _u
}

// AddPassengerID adds value to the "passenger_id" field.
func (_u *BidSessionUpdateOne) AddPassengerID(v int) *BidSessionUpdateOne {
	_u.mutation.AddPassengerID(v)
	return _u
}

// SetRideType sets the "ride_type" field.
func (_u *BidSessionUpdateOne) SetRideType(v string) *BidSessionUpdateOne {
	_u.mutation.SetRideType(v)
	return _u
}

// SetNillableRideType sets the "ride_type" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableRideType(v *string) *BidSessionUpdateOne {
	if v != nil {
		_u.SetRideType(*v)
	}
	return _u
}

// SetPickupLatitude sets the "pickup_latitude" field.
func (_u *BidSessionUpdateOne) SetPickupLatitude(v float64) *BidSessionUpdateOne {
	_u.mutation.ResetPickupLatitude()
	_u.mutation.SetPickupLatitude(v)
	return _u
}

// SetNillablePickupLatitude sets the "pickup_latitude" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillablePickupLatitude(v *float64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetPickupLatitude(*v)
	}
	return _u
}

// AddPickupLatitude adds value to the "pickup_latitude" field.
func (_u *BidSessionUpdateOne) AddPickupLatitude(v float64) *BidSessionUpdateOne {
	_u.mutation.AddPickupLatitude(v)
	return _u
}

// SetPickupLongitude sets the "pickup_longitude" field.
func (_u *BidSessionUpdateOne) SetPickupLongitude(v float64) *BidSessionUpdateOne {
	_u.mutation.ResetPickupLongitude()
	_u.mutation.SetPickupLongitude(v)
	return _u
}

// SetNillablePickupLongitude sets the "pickup_longitude" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillablePickupLongitude(v *float64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetPickupLongitude(*v)
	}
	return _u
}

// AddPickupLongitude adds value to the "pickup_longitude" field.
func (_u *BidSessionUpdateOne) AddPickupLongitude(v float64) *BidSessionUpdateOne {
	_u.mutation.AddPickupLongitude(v)
	return _u
}

// SetPickupName sets the "pickup_name" field.
func (_u *BidSessionUpdateOne) SetPickupName(v string) *BidSessionUpdateOne {
	_u.mutation.SetPickupName(v)
	return _u
}

// SetNillablePickupName sets the "pickup_name" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillablePickupName(v *string) *BidSessionUpdateOne {
	if v != nil {
		_u.SetPickupName(*v)
	}
	return _u
}

// SetDropoffLatitude sets the "dropoff_latitude" field.
func (_u *BidSessionUpdateOne) SetDropoffLatitude(v float64) *BidSessionUpdateOne {
	_u.mutation.ResetDropoffLatitude()
	_u.mutation.SetDropoffLatitude(v)
	return _u
}

// SetNillableDropoffLatitude sets the "dropoff_latitude" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableDropoffLatitude(v *float64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetDropoffLatitude(*v)
	}
	return _u
}

// AddDropoffLatitude adds value to the "dropoff_latitude" field.
func (_u *BidSessionUpdateOne) AddDropoffLatitude(v float64) *BidSessionUpdateOne {
	_u.mutation.AddDropoffLatitude(v)
	return _u
}

// SetDropoffLongitude sets the "dropoff_longitude" field.
func (_u *BidSessionUpdateOne) SetDropoffLongitude(v float64) *BidSessionUpdateOne {
	_u.mutation.ResetDropoffLongitude()
	_u.mutation.SetDropoffLongitude(v)
	return _u
}

// SetNillableDropoffLongitude sets the "dropoff_longitude" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableDropoffLongitude(v *float64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetDropoffLongitude(*v)
	}
	return _u
}

// AddDropoffLongitude adds value to the "dropoff_longitude" field.
func (_u *BidSessionUpdateOne) AddDropoffLongitude(v float64) *BidSessionUpdateOne {
	_u.mutation.AddDropoffLongitude(v)
	return _u
}

// SetDropoffName sets the "dropoff_name" field.
func (_u *BidSessionUpdateOne) SetDropoffName(v string) *BidSessionUpdateOne {
	_u.mutation.SetDropoffName(v)
	return _u
}

// SetNillableDropoffName sets the "dropoff_name" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableDropoffName(v *string) *BidSessionUpdateOne {
	if v != nil {
		_u.SetDropoffName(*v)
	}
	return _u
}

// SetPassengerNote sets the "passenger_note" field.
func (_u *BidSessionUpdateOne) SetPassengerNote(v string) *BidSessionUpdateOne {
	_u.mutation.SetPassengerNote(v)
	return _u
}

// SetNillablePassengerNote sets the "passenger_note" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillablePassengerNote(v *string) *BidSessionUpdateOne {
	if v != nil {
		_u.SetPassengerNote(*v)
	}
	return _u
}

// ClearPassengerNote clears the value of the "passenger_note" field.
func (_u *BidSessionUpdateOne) ClearPassengerNote() *BidSessionUpdateOne {
	_u.mutation.ClearPassengerNote()
	return _u
}

// SetDistanceKm sets the "distance_km" field.
func (_u *BidSessionUpdateOne) SetDistanceKm(v float64) *BidSessionUpdateOne {
	_u.mutation.ResetDistanceKm()
	_u.mutation.SetDistanceKm(v)
	return _u
}

// SetNillableDistanceKm sets the "distance_km" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableDistanceKm(v *float64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetDistanceKm(*v)
	}
	return _u
}

// AddDistanceKm adds value to the "distance_km" field.
func (_u *BidSessionUpdateOne) AddDistanceKm(v float64) *BidSessionUpdateOne {
	_u.mutation.AddDistanceKm(v)
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *BidSessionUpdateOne) SetDurationMinutes(v float64) *BidSessionUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableDurationMinutes(v *float64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *BidSessionUpdateOne) AddDurationMinutes(v float64) *BidSessionUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetOfferedFareCentavos sets the "offered_fare_centavos" field.
func (_u *BidSessionUpdateOne) SetOfferedFareCentavos(v int64) *BidSessionUpdateOne {
	_u.mutation.ResetOfferedFareCentavos()
	_u.mutation.SetOfferedFareCentavos(v)
	return _u
}

// SetNillableOfferedFareCentavos sets the "offered_fare_centavos" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableOfferedFareCentavos(v *int64) *BidSessionUpdateOne {
	if v != nil {
		_u.SetOfferedFareCentavos(*v)
	}
	return _u
}

// AddOfferedFareCentavos adds value to the "offered_fare_centavos" field.
func (_u *BidSessionUpdateOne) AddOfferedFareCentavos(v int64) *BidSessionUpdateOne {
	_u.mutation.AddOfferedFareCentavos(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BidSessionUpdateOne) SetStatus(v string) *BidSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableStatus(v *string) *BidSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTargetDriverID sets the "target_driver_id" field.
func (_u *BidSessionUpdateOne) SetTargetDriverID(v int) *BidSessionUpdateOne {
	_u.mutation.ResetTargetDriverID()
	_u.mutation.SetTargetDriverID(v)
	return _u
}

// SetNillableTargetDriverID sets the "target_driver_id" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableTargetDriverID(v *int) *BidSessionUpdateOne {
	if v != nil {
		_u.SetTargetDriverID(*v)
	}
	return _u
}

// AddTargetDriverID adds value to the "target_driver_id" field.
func (_u *BidSessionUpdateOne) AddTargetDriverID(v int) *BidSessionUpdateOne {
	_u.mutation.AddTargetDriverID(v)
	return _u
}

// ClearTargetDriverID clears the value of the "target_driver_id" field.
func (_u *BidSessionUpdateOne) ClearTargetDriverID() *BidSessionUpdateOne {
	_u.mutation.ClearTargetDriverID()
	return _u
}

// SetAcceptedDriverID sets the "accepted_driver_id" field.
func (_u *BidSessionUpdateOne) SetAcceptedDriverID(v int) *BidSessionUpdateOne {
	_u.mutation.ResetAcceptedDriverID()
	_u.mutation.SetAcceptedDriverID(v)
	return _u
}

// SetNillableAcceptedDriverID sets the "accepted_driver_id" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableAcceptedDriverID(v *int) *BidSessionUpdateOne {
	if v != nil {
		_u.SetAcceptedDriverID(*v)
	}
	return _u
}

// AddAcceptedDriverID adds value to the "accepted_driver_id" field.
func (_u *BidSessionUpdateOne) AddAcceptedDriverID(v int) *BidSessionUpdateOne {
	_u.mutation.AddAcceptedDriverID(v)
	return _u
}

// ClearAcceptedDriverID clears the value of the "accepted_driver_id" field.
func (_u *BidSessionUpdateOne) ClearAcceptedDriverID() *BidSessionUpdateOne {
	_u.mutation.ClearAcceptedDriverID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BidSessionUpdateOne) SetExpiresAt(v time.Time) *BidSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *BidSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BidSessionUpdateOne) SetCreatedAt(v time.Time) *BidSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BidSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *BidSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the BidSessionMutation object of the builder.
func (_u *BidSessionUpdateOne) Mutation() *BidSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the BidSessionUpdate builder.
func (_u *BidSessionUpdateOne) Where(ps ...predicate.BidSession) *BidSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BidSessionUpdateOne) Select(field string, fields ...string) *BidSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BidSession entity.
func (_u *BidSessionUpdateOne) Save(ctx context.Context) (*BidSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BidSessionUpdateOne) SaveX(ctx context.Context) *BidSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BidSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BidSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BidSessionUpdateOne) check() error {
	if v, ok := _u.mutation.PassengerID(); ok {
		if err := bidsession.PassengerIDValidator(v); err != nil {
			return &ValidationError{Name: "passenger_id", err: fmt.Errorf(`ent: validator failed for field "BidSession.passenger_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PassengerNote(); ok {
		if err := bidsession.PassengerNoteValidator(v); err != nil {
			return &ValidationError{Name: "passenger_note", err: fmt.Errorf(`ent: validator failed for field "BidSession.passenger_note": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OfferedFareCentavos(); ok {
		if err := bidsession.OfferedFareCentavosValidator(v); err != nil {
			return &ValidationError{Name: "offered_fare_centavos", err: fmt.Errorf(`ent: validator failed for field "BidSession.offered_fare_centavos": %w`, err)}
		}
	}
	return nil
}

func (_u *BidSessionUpdateOne) sqlSave(ctx context.Context) (_node *BidSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bidsession.Table, bidsession.Columns, sqlgraph.NewFieldSpec(bidsession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BidSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bidsession.FieldID)
		for _, f := range fields {
			if !bidsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bidsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PassengerID(); ok {
		_spec.SetField(bidsession.FieldPassengerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassengerID(); ok {
		_spec.AddField(bidsession.FieldPassengerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RideType(); ok {
		_spec.SetField(bidsession.FieldRideType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PickupLatitude(); ok {
		_spec.SetField(bidsession.FieldPickupLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPickupLatitude(); ok {
		_spec.AddField(bidsession.FieldPickupLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PickupLongitude(); ok {
		_spec.SetField(bidsession.FieldPickupLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPickupLongitude(); ok {
		_spec.AddField(bidsession.FieldPickupLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PickupName(); ok {
		_spec.SetField(bidsession.FieldPickupName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DropoffLatitude(); ok {
		_spec.SetField(bidsession.FieldDropoffLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDropoffLatitude(); ok {
		_spec.AddField(bidsession.FieldDropoffLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DropoffLongitude(); ok {
		_spec.SetField(bidsession.FieldDropoffLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDropoffLongitude(); ok {
		_spec.AddField(bidsession.FieldDropoffLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DropoffName(); ok {
		_spec.SetField(bidsession.FieldDropoffName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassengerNote(); ok {
		_spec.SetField(bidsession.FieldPassengerNote, field.TypeString, value)
	}
	if _u.mutation.PassengerNoteCleared() {
		_spec.ClearField(bidsession.FieldPassengerNote, field.TypeString)
	}
	if value, ok := _u.mutation.DistanceKm(); ok {
		_spec.SetField(bidsession.FieldDistanceKm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDistanceKm(); ok {
		_spec.AddField(bidsession.FieldDistanceKm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(bidsession.FieldDurationMinutes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(bidsession.FieldDurationMinutes, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OfferedFareCentavos(); ok {
		_spec.SetField(bidsession.FieldOfferedFareCentavos, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOfferedFareCentavos(); ok {
		_spec.AddField(bidsession.FieldOfferedFareCentavos, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bidsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetDriverID(); ok {
		_spec.SetField(bidsession.FieldTargetDriverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetDriverID(); ok {
		_spec.AddField(bidsession.FieldTargetDriverID, field.TypeInt, value)
	}
	if _u.mutation.TargetDriverIDCleared() {
		_spec.ClearField(bidsession.FieldTargetDriverID, field.TypeInt)
	}
	if value, ok := _u.mutation.AcceptedDriverID(); ok {
		_spec.SetField(bidsession.FieldAcceptedDriverID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAcceptedDriverID(); ok {
		_spec.AddField(bidsession.FieldAcceptedDriverID, field.TypeInt, value)
	}
	if _u.mutation.AcceptedDriverIDCleared() {
		_spec.ClearField(bidsession.FieldAcceptedDriverID, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bidsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bidsession.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &BidSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bidsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
