// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Easy-Bao/DrivingApp/server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/Easy-Bao/DrivingApp/server/ent/auditevent"
	"github.com/Easy-Bao/DrivingApp/server/ent/bid"
	"github.com/Easy-Bao/DrivingApp/server/ent/bidoffer"
	"github.com/Easy-Bao/DrivingApp/server/ent/bidsession"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverdocument"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverprofile"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverwalletaccount"
	"github.com/Easy-Bao/DrivingApp/server/ent/notification"
	"github.com/Easy-Bao/DrivingApp/server/ent/passengerprofile"
	"github.com/Easy-Bao/DrivingApp/server/ent/passengerreview"
	"github.com/Easy-Bao/DrivingApp/server/ent/privateobject"
	"github.com/Easy-Bao/DrivingApp/server/ent/refreshsession"
	"github.com/Easy-Bao/DrivingApp/server/ent/review"
	"github.com/Easy-Bao/DrivingApp/server/ent/ride"
	"github.com/Easy-Bao/DrivingApp/server/ent/ridesettlement"
	"github.com/Easy-Bao/DrivingApp/server/ent/user"
	"github.com/Easy-Bao/DrivingApp/server/ent/walletledger"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AuditEvent is the client for interacting with the AuditEvent builders.
	AuditEvent *AuditEventClient
	// Bid is the client for interacting with the Bid builders.
	Bid *BidClient
	// BidOffer is the client for interacting with the BidOffer builders.
	BidOffer *BidOfferClient
	// BidSession is the client for interacting with the BidSession builders.
	BidSession *BidSessionClient
	// DriverDocument is the client for interacting with the DriverDocument builders.
	DriverDocument *DriverDocumentClient
	// DriverProfile is the client for interacting with the DriverProfile builders.
	DriverProfile *DriverProfileClient
	// DriverWalletAccount is the client for interacting with the DriverWalletAccount builders.
	DriverWalletAccount *DriverWalletAccountClient
	// Notification is the client for interacting with the Notification builders.
	Notification *NotificationClient
	// PassengerProfile is the client for interacting with the PassengerProfile builders.
	PassengerProfile *PassengerProfileClient
	// PassengerReview is the client for interacting with the PassengerReview builders.
	PassengerReview *PassengerReviewClient
	// PrivateObject is the client for interacting with the PrivateObject builders.
	PrivateObject *PrivateObjectClient
	// RefreshSession is the client for interacting with the RefreshSession builders.
	RefreshSession *RefreshSessionClient
	// Review is the client for interacting with the Review builders.
	Review *ReviewClient
	// Ride is the client for interacting with the Ride builders.
	Ride *RideClient
	// RideSettlement is the client for interacting with the RideSettlement builders.
	RideSettlement *RideSettlementClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// WalletLedger is the client for interacting with the WalletLedger builders.
	WalletLedger *WalletLedgerClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AuditEvent = NewAuditEventClient(c.config)
	c.Bid = NewBidClient(c.config)
	c.BidOffer = NewBidOfferClient(c.config)
	c.BidSession = NewBidSessionClient(c.config)
	c.DriverDocument = NewDriverDocumentClient(c.config)
	c.DriverProfile = NewDriverProfileClient(c.config)
	c.DriverWalletAccount = NewDriverWalletAccountClient(c.config)
	c.Notification = NewNotificationClient(c.config)
	c.PassengerProfile = NewPassengerProfileClient(c.config)
	c.PassengerReview = NewPassengerReviewClient(c.config)
	c.PrivateObject = NewPrivateObjectClient(c.config)
	c.RefreshSession = NewRefreshSessionClient(c.config)
	c.Review = NewReviewClient(c.config)
	c.Ride = NewRideClient(c.config)
	c.RideSettlement = NewRideSettlementClient(c.config)
	c.User = NewUserClient(c.config)
	c.WalletLedger = NewWalletLedgerClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		AuditEvent:          NewAuditEventClient(cfg),
		Bid:                 NewBidClient(cfg),
		BidOffer:            NewBidOfferClient(cfg),
		BidSession:          NewBidSessionClient(cfg),
		DriverDocument:      NewDriverDocumentClient(cfg),
		DriverProfile:       NewDriverProfileClient(cfg),
		DriverWalletAccount: NewDriverWalletAccountClient(cfg),
		Notification:        NewNotificationClient(cfg),
		PassengerProfile:    NewPassengerProfileClient(cfg),
		PassengerReview:     NewPassengerReviewClient(cfg),
		PrivateObject:       NewPrivateObjectClient(cfg),
		RefreshSession:      NewRefreshSessionClient(cfg),
		Review:              NewReviewClient(cfg),
		Ride:                NewRideClient(cfg),
		RideSettlement:      NewRideSettlementClient(cfg),
		User:                NewUserClient(cfg),
		WalletLedger:        NewWalletLedgerClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		AuditEvent:          NewAuditEventClient(cfg),
		Bid:                 NewBidClient(cfg),
		BidOffer:            NewBidOfferClient(cfg),
		BidSession:          NewBidSessionClient(cfg),
		DriverDocument:      NewDriverDocumentClient(cfg),
		DriverProfile:       NewDriverProfileClient(cfg),
		DriverWalletAccount: NewDriverWalletAccountClient(cfg),
		Notification:        NewNotificationClient(cfg),
		PassengerProfile:    NewPassengerProfileClient(cfg),
		PassengerReview:     NewPassengerReviewClient(cfg),
		PrivateObject:       NewPrivateObjectClient(cfg),
		RefreshSession:      NewRefreshSessionClient(cfg),
		Review:              NewReviewClient(cfg),
		Ride:                NewRideClient(cfg),
		RideSettlement:      NewRideSettlementClient(cfg),
		User:                NewUserClient(cfg),
		WalletLedger:        NewWalletLedgerClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AuditEvent.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AuditEvent, c.Bid, c.BidOffer, c.BidSession, c.DriverDocument,
		c.DriverProfile, c.DriverWalletAccount, c.Notification, c.PassengerProfile,
		c.PassengerReview, c.PrivateObject, c.RefreshSession, c.Review, c.Ride,
		c.RideSettlement, c.User, c.WalletLedger,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AuditEvent, c.Bid, c.BidOffer, c.BidSession, c.DriverDocument,
		c.DriverProfile, c.DriverWalletAccount, c.Notification, c.PassengerProfile,
		c.PassengerReview, c.PrivateObject, c.RefreshSession, c.Review, c.Ride,
		c.RideSettlement, c.User, c.WalletLedger,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AuditEventMutation:
		return c.AuditEvent.mutate(ctx, m)
	case *BidMutation:
		return c.Bid.mutate(ctx, m)
	case *BidOfferMutation:
		return c.BidOffer.mutate(ctx, m)
	case *BidSessionMutation:
		return c.BidSession.mutate(ctx, m)
	case *DriverDocumentMutation:
		return c.DriverDocument.mutate(ctx, m)
	case *DriverProfileMutation:
		return c.DriverProfile.mutate(ctx, m)
	case *DriverWalletAccountMutation:
		return c.DriverWalletAccount.mutate(ctx, m)
	case *NotificationMutation:
		return c.Notification.mutate(ctx, m)
	case *PassengerProfileMutation:
		return c.PassengerProfile.mutate(ctx, m)
	case *PassengerReviewMutation:
		return c.PassengerReview.mutate(ctx, m)
	case *PrivateObjectMutation:
		return c.PrivateObject.mutate(ctx, m)
	case *RefreshSessionMutation:
		return c.RefreshSession.mutate(ctx, m)
	case *ReviewMutation:
		return c.Review.mutate(ctx, m)
	case *RideMutation:
		return c.Ride.mutate(ctx, m)
	case *RideSettlementMutation:
		return c.RideSettlement.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *WalletLedgerMutation:
		return c.WalletLedger.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AuditEventClient is a client for the AuditEvent schema.
type AuditEventClient struct {
	config
}

// NewAuditEventClient returns a client for the AuditEvent from the given config.
func NewAuditEventClient(c config) *AuditEventClient {
	return &AuditEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditevent.Hooks(f(g(h())))`.
func (c *AuditEventClient) Use(hooks ...Hook) {
	c.hooks.AuditEvent = append(c.hooks.AuditEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditevent.Intercept(f(g(h())))`.
func (c *AuditEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditEvent = append(c.inters.AuditEvent, interceptors...)
}

// Create returns a builder for creating a AuditEvent entity.
func (c *AuditEventClient) Create() *AuditEventCreate {
	mutation := newAuditEventMutation(c.config, OpCreate)
	return &AuditEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditEvent entities.
func (c *AuditEventClient) CreateBulk(builders ...*AuditEventCreate) *AuditEventCreateBulk {
	return &AuditEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditEventClient) MapCreateBulk(slice any, setFunc func(*AuditEventCreate, int)) *AuditEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditEventCreateBulk{err: fmt.Errorf("calling to AuditEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditEvent.
func (c *AuditEventClient) Update() *AuditEventUpdate {
	mutation := newAuditEventMutation(c.config, OpUpdate)
	return &AuditEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditEventClient) UpdateOne(_m *AuditEvent) *AuditEventUpdateOne {
	mutation := newAuditEventMutation(c.config, OpUpdateOne, withAuditEvent(_m))
	return &AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditEventClient) UpdateOneID(id int) *AuditEventUpdateOne {
	mutation := newAuditEventMutation(c.config, OpUpdateOne, withAuditEventID(id))
	return &AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditEvent.
func (c *AuditEventClient) Delete() *AuditEventDelete {
	mutation := newAuditEventMutation(c.config, OpDelete)
	return &AuditEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditEventClient) DeleteOne(_m *AuditEvent) *AuditEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditEventClient) DeleteOneID(id int) *AuditEventDeleteOne {
	builder := c.Delete().Where(auditevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditEventDeleteOne{builder}
}

// Query returns a query builder for AuditEvent.
func (c *AuditEventClient) Query() *AuditEventQuery {
	return &AuditEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditEvent entity by its id.
func (c *AuditEventClient) Get(ctx context.Context, id int) (*AuditEvent, error) {
	return c.Query().Where(auditevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditEventClient) GetX(ctx context.Context, id int) *AuditEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditEventClient) Hooks() []Hook {
	return c.hooks.AuditEvent
}

// Interceptors returns the client interceptors.
func (c *AuditEventClient) Interceptors() []Interceptor {
	return c.inters.AuditEvent
}

func (c *AuditEventClient) mutate(ctx context.Context, m *AuditEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditEvent mutation op: %q", m.Op())
	}
}

// BidClient is a client for the Bid schema.
type BidClient struct {
	config
}

// NewBidClient returns a client for the Bid from the given config.
func NewBidClient(c config) *BidClient {
	return &BidClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bid.Hooks(f(g(h())))`.
func (c *BidClient) Use(hooks ...Hook) {
	c.hooks.Bid = append(c.hooks.Bid, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bid.Intercept(f(g(h())))`.
func (c *BidClient) Intercept(interceptors ...Interceptor) {
	c.inters.Bid = append(c.inters.Bid, interceptors...)
}

// Create returns a builder for creating a Bid entity.
func (c *BidClient) Create() *BidCreate {
	mutation := newBidMutation(c.config, OpCreate)
	return &BidCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bid entities.
func (c *BidClient) CreateBulk(builders ...*BidCreate) *BidCreateBulk {
	return &BidCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BidClient) MapCreateBulk(slice any, setFunc func(*BidCreate, int)) *BidCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BidCreateBulk{err: fmt.Errorf("calling to BidClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BidCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BidCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bid.
func (c *BidClient) Update() *BidUpdate {
	mutation := newBidMutation(c.config, OpUpdate)
	return &BidUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BidClient) UpdateOne(_m *Bid) *BidUpdateOne {
	mutation := newBidMutation(c.config, OpUpdateOne, withBid(_m))
	return &BidUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BidClient) UpdateOneID(id int) *BidUpdateOne {
	mutation := newBidMutation(c.config, OpUpdateOne, withBidID(id))
	return &BidUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bid.
func (c *BidClient) Delete() *BidDelete {
	mutation := newBidMutation(c.config, OpDelete)
	return &BidDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BidClient) DeleteOne(_m *Bid) *BidDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BidClient) DeleteOneID(id int) *BidDeleteOne {
	builder := c.Delete().Where(bid.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BidDeleteOne{builder}
}

// Query returns a query builder for Bid.
func (c *BidClient) Query() *BidQuery {
	return &BidQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBid},
		inters: c.Interceptors(),
	}
}

// Get returns a Bid entity by its id.
func (c *BidClient) Get(ctx context.Context, id int) (*Bid, error) {
	return c.Query().Where(bid.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BidClient) GetX(ctx context.Context, id int) *Bid {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BidClient) Hooks() []Hook {
	return c.hooks.Bid
}

// Interceptors returns the client interceptors.
func (c *BidClient) Interceptors() []Interceptor {
	return c.inters.Bid
}

func (c *BidClient) mutate(ctx context.Context, m *BidMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BidCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BidUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BidUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BidDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Bid mutation op: %q", m.Op())
	}
}

// BidOfferClient is a client for the BidOffer schema.
type BidOfferClient struct {
	config
}

// NewBidOfferClient returns a client for the BidOffer from the given config.
func NewBidOfferClient(c config) *BidOfferClient {
	return &BidOfferClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bidoffer.Hooks(f(g(h())))`.
func (c *BidOfferClient) Use(hooks ...Hook) {
	c.hooks.BidOffer = append(c.hooks.BidOffer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bidoffer.Intercept(f(g(h())))`.
func (c *BidOfferClient) Intercept(interceptors ...Interceptor) {
	c.inters.BidOffer = append(c.inters.BidOffer, interceptors...)
}

// Create returns a builder for creating a BidOffer entity.
func (c *BidOfferClient) Create() *BidOfferCreate {
	mutation := newBidOfferMutation(c.config, OpCreate)
	return &BidOfferCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BidOffer entities.
func (c *BidOfferClient) CreateBulk(builders ...*BidOfferCreate) *BidOfferCreateBulk {
	return &BidOfferCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BidOfferClient) MapCreateBulk(slice any, setFunc func(*BidOfferCreate, int)) *BidOfferCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BidOfferCreateBulk{err: fmt.Errorf("calling to BidOfferClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BidOfferCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BidOfferCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BidOffer.
func (c *BidOfferClient) Update() *BidOfferUpdate {
	mutation := newBidOfferMutation(c.config, OpUpdate)
	return &BidOfferUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BidOfferClient) UpdateOne(_m *BidOffer) *BidOfferUpdateOne {
	mutation := newBidOfferMutation(c.config, OpUpdateOne, withBidOffer(_m))
	return &BidOfferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BidOfferClient) UpdateOneID(id int) *BidOfferUpdateOne {
	mutation := newBidOfferMutation(c.config, OpUpdateOne, withBidOfferID(id))
	return &BidOfferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BidOffer.
func (c *BidOfferClient) Delete() *BidOfferDelete {
	mutation := newBidOfferMutation(c.config, OpDelete)
	return &BidOfferDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BidOfferClient) DeleteOne(_m *BidOffer) *BidOfferDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BidOfferClient) DeleteOneID(id int) *BidOfferDeleteOne {
	builder := c.Delete().Where(bidoffer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BidOfferDeleteOne{builder}
}

// Query returns a query builder for BidOffer.
func (c *BidOfferClient) Query() *BidOfferQuery {
	return &BidOfferQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBidOffer},
		inters: c.Interceptors(),
	}
}

// Get returns a BidOffer entity by its id.
func (c *BidOfferClient) Get(ctx context.Context, id int) (*BidOffer, error) {
	return c.Query().Where(bidoffer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BidOfferClient) GetX(ctx context.Context, id int) *BidOffer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BidOfferClient) Hooks() []Hook {
	return c.hooks.BidOffer
}

// Interceptors returns the client interceptors.
func (c *BidOfferClient) Interceptors() []Interceptor {
	return c.inters.BidOffer
}

func (c *BidOfferClient) mutate(ctx context.Context, m *BidOfferMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BidOfferCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BidOfferUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BidOfferUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BidOfferDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BidOffer mutation op: %q", m.Op())
	}
}

// BidSessionClient is a client for the BidSession schema.
type BidSessionClient struct {
	config
}

// NewBidSessionClient returns a client for the BidSession from the given config.
func NewBidSessionClient(c config) *BidSessionClient {
	return &BidSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bidsession.Hooks(f(g(h())))`.
func (c *BidSessionClient) Use(hooks ...Hook) {
	c.hooks.BidSession = append(c.hooks.BidSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bidsession.Intercept(f(g(h())))`.
func (c *BidSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.BidSession = append(c.inters.BidSession, interceptors...)
}

// Create returns a builder for creating a BidSession entity.
func (c *BidSessionClient) Create() *BidSessionCreate {
	mutation := newBidSessionMutation(c.config, OpCreate)
	return &BidSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BidSession entities.
func (c *BidSessionClient) CreateBulk(builders ...*BidSessionCreate) *BidSessionCreateBulk {
	return &BidSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BidSessionClient) MapCreateBulk(slice any, setFunc func(*BidSessionCreate, int)) *BidSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BidSessionCreateBulk{err: fmt.Errorf("calling to BidSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BidSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BidSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BidSession.
func (c *BidSessionClient) Update() *BidSessionUpdate {
	mutation := newBidSessionMutation(c.config, OpUpdate)
	return &BidSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BidSessionClient) UpdateOne(_m *BidSession) *BidSessionUpdateOne {
	mutation := newBidSessionMutation(c.config, OpUpdateOne, withBidSession(_m))
	return &BidSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BidSessionClient) UpdateOneID(id int) *BidSessionUpdateOne {
	mutation := newBidSessionMutation(c.config, OpUpdateOne, withBidSessionID(id))
	return &BidSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BidSession.
func (c *BidSessionClient) Delete() *BidSessionDelete {
	mutation := newBidSessionMutation(c.config, OpDelete)
	return &BidSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BidSessionClient) DeleteOne(_m *BidSession) *BidSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BidSessionClient) DeleteOneID(id int) *BidSessionDeleteOne {
	builder := c.Delete().Where(bidsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BidSessionDeleteOne{builder}
}

// Query returns a query builder for BidSession.
func (c *BidSessionClient) Query() *BidSessionQuery {
	return &BidSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBidSession},
		inters: c.Interceptors(),
	}
}

// Get returns a BidSession entity by its id.
func (c *BidSessionClient) Get(ctx context.Context, id int) (*BidSession, error) {
	return c.Query().Where(bidsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BidSessionClient) GetX(ctx context.Context, id int) *BidSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BidSessionClient) Hooks() []Hook {
	return c.hooks.BidSession
}

// Interceptors returns the client interceptors.
func (c *BidSessionClient) Interceptors() []Interceptor {
	return c.inters.BidSession
}

func (c *BidSessionClient) mutate(ctx context.Context, m *BidSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BidSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BidSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BidSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BidSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BidSession mutation op: %q", m.Op())
	}
}

// DriverDocumentClient is a client for the DriverDocument schema.
type DriverDocumentClient struct {
	config
}

// NewDriverDocumentClient returns a client for the DriverDocument from the given config.
func NewDriverDocumentClient(c config) *DriverDocumentClient {
	return &DriverDocumentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `driverdocument.Hooks(f(g(h())))`.
func (c *DriverDocumentClient) Use(hooks ...Hook) {
	c.hooks.DriverDocument = append(c.hooks.DriverDocument, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `driverdocument.Intercept(f(g(h())))`.
func (c *DriverDocumentClient) Intercept(interceptors ...Interceptor) {
	c.inters.DriverDocument = append(c.inters.DriverDocument, interceptors...)
}

// Create returns a builder for creating a DriverDocument entity.
func (c *DriverDocumentClient) Create() *DriverDocumentCreate {
	mutation := newDriverDocumentMutation(c.config, OpCreate)
	return &DriverDocumentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DriverDocument entities.
func (c *DriverDocumentClient) CreateBulk(builders ...*DriverDocumentCreate) *DriverDocumentCreateBulk {
	return &DriverDocumentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DriverDocumentClient) MapCreateBulk(slice any, setFunc func(*DriverDocumentCreate, int)) *DriverDocumentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DriverDocumentCreateBulk{err: fmt.Errorf("calling to DriverDocumentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DriverDocumentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DriverDocumentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DriverDocument.
func (c *DriverDocumentClient) Update() *DriverDocumentUpdate {
	mutation := newDriverDocumentMutation(c.config, OpUpdate)
	return &DriverDocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DriverDocumentClient) UpdateOne(_m *DriverDocument) *DriverDocumentUpdateOne {
	mutation := newDriverDocumentMutation(c.config, OpUpdateOne, withDriverDocument(_m))
	return &DriverDocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DriverDocumentClient) UpdateOneID(id int) *DriverDocumentUpdateOne {
	mutation := newDriverDocumentMutation(c.config, OpUpdateOne, withDriverDocumentID(id))
	return &DriverDocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DriverDocument.
func (c *DriverDocumentClient) Delete() *DriverDocumentDelete {
	mutation := newDriverDocumentMutation(c.config, OpDelete)
	return &DriverDocumentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DriverDocumentClient) DeleteOne(_m *DriverDocument) *DriverDocumentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DriverDocumentClient) DeleteOneID(id int) *DriverDocumentDeleteOne {
	builder := c.Delete().Where(driverdocument.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DriverDocumentDeleteOne{builder}
}

// Query returns a query builder for DriverDocument.
func (c *DriverDocumentClient) Query() *DriverDocumentQuery {
	return &DriverDocumentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDriverDocument},
		inters: c.Interceptors(),
	}
}

// Get returns a DriverDocument entity by its id.
func (c *DriverDocumentClient) Get(ctx context.Context, id int) (*DriverDocument, error) {
	return c.Query().Where(driverdocument.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DriverDocumentClient) GetX(ctx context.Context, id int) *DriverDocument {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DriverDocumentClient) Hooks() []Hook {
	return c.hooks.DriverDocument
}

// Interceptors returns the client interceptors.
func (c *DriverDocumentClient) Interceptors() []Interceptor {
	return c.inters.DriverDocument
}

func (c *DriverDocumentClient) mutate(ctx context.Context, m *DriverDocumentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DriverDocumentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DriverDocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DriverDocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DriverDocumentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DriverDocument mutation op: %q", m.Op())
	}
}

// DriverProfileClient is a client for the DriverProfile schema.
type DriverProfileClient struct {
	config
}

// NewDriverProfileClient returns a client for the DriverProfile from the given config.
func NewDriverProfileClient(c config) *DriverProfileClient {
	return &DriverProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `driverprofile.Hooks(f(g(h())))`.
func (c *DriverProfileClient) Use(hooks ...Hook) {
	c.hooks.DriverProfile = append(c.hooks.DriverProfile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `driverprofile.Intercept(f(g(h())))`.
func (c *DriverProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.DriverProfile = append(c.inters.DriverProfile, interceptors...)
}

// Create returns a builder for creating a DriverProfile entity.
func (c *DriverProfileClient) Create() *DriverProfileCreate {
	mutation := newDriverProfileMutation(c.config, OpCreate)
	return &DriverProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DriverProfile entities.
func (c *DriverProfileClient) CreateBulk(builders ...*DriverProfileCreate) *DriverProfileCreateBulk {
	return &DriverProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DriverProfileClient) MapCreateBulk(slice any, setFunc func(*DriverProfileCreate, int)) *DriverProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DriverProfileCreateBulk{err: fmt.Errorf("calling to DriverProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DriverProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DriverProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DriverProfile.
func (c *DriverProfileClient) Update() *DriverProfileUpdate {
	mutation := newDriverProfileMutation(c.config, OpUpdate)
	return &DriverProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DriverProfileClient) UpdateOne(_m *DriverProfile) *DriverProfileUpdateOne {
	mutation := newDriverProfileMutation(c.config, OpUpdateOne, withDriverProfile(_m))
	return &DriverProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DriverProfileClient) UpdateOneID(id int) *DriverProfileUpdateOne {
	mutation := newDriverProfileMutation(c.config, OpUpdateOne, withDriverProfileID(id))
	return &DriverProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DriverProfile.
func (c *DriverProfileClient) Delete() *DriverProfileDelete {
	mutation := newDriverProfileMutation(c.config, OpDelete)
	return &DriverProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DriverProfileClient) DeleteOne(_m *DriverProfile) *DriverProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DriverProfileClient) DeleteOneID(id int) *DriverProfileDeleteOne {
	builder := c.Delete().Where(driverprofile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DriverProfileDeleteOne{builder}
}

// Query returns a query builder for DriverProfile.
func (c *DriverProfileClient) Query() *DriverProfileQuery {
	return &DriverProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDriverProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a DriverProfile entity by its id.
func (c *DriverProfileClient) Get(ctx context.Context, id int) (*DriverProfile, error) {
	return c.Query().Where(driverprofile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DriverProfileClient) GetX(ctx context.Context, id int) *DriverProfile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DriverProfileClient) Hooks() []Hook {
	return c.hooks.DriverProfile
}

// Interceptors returns the client interceptors.
func (c *DriverProfileClient) Interceptors() []Interceptor {
	return c.inters.DriverProfile
}

func (c *DriverProfileClient) mutate(ctx context.Context, m *DriverProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DriverProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DriverProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DriverProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DriverProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DriverProfile mutation op: %q", m.Op())
	}
}

// DriverWalletAccountClient is a client for the DriverWalletAccount schema.
type DriverWalletAccountClient struct {
	config
}

// NewDriverWalletAccountClient returns a client for the DriverWalletAccount from the given config.
func NewDriverWalletAccountClient(c config) *DriverWalletAccountClient {
	return &DriverWalletAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `driverwalletaccount.Hooks(f(g(h())))`.
func (c *DriverWalletAccountClient) Use(hooks ...Hook) {
	c.hooks.DriverWalletAccount = append(c.hooks.DriverWalletAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `driverwalletaccount.Intercept(f(g(h())))`.
func (c *DriverWalletAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.DriverWalletAccount = append(c.inters.DriverWalletAccount, interceptors...)
}

// Create returns a builder for creating a DriverWalletAccount entity.
func (c *DriverWalletAccountClient) Create() *DriverWalletAccountCreate {
	mutation := newDriverWalletAccountMutation(c.config, OpCreate)
	return &DriverWalletAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DriverWalletAccount entities.
func (c *DriverWalletAccountClient) CreateBulk(builders ...*DriverWalletAccountCreate) *DriverWalletAccountCreateBulk {
	return &DriverWalletAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DriverWalletAccountClient) MapCreateBulk(slice any, setFunc func(*DriverWalletAccountCreate, int)) *DriverWalletAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DriverWalletAccountCreateBulk{err: fmt.Errorf("calling to DriverWalletAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DriverWalletAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DriverWalletAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DriverWalletAccount.
func (c *DriverWalletAccountClient) Update() *DriverWalletAccountUpdate {
	mutation := newDriverWalletAccountMutation(c.config, OpUpdate)
	return &DriverWalletAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DriverWalletAccountClient) UpdateOne(_m *DriverWalletAccount) *DriverWalletAccountUpdateOne {
	mutation := newDriverWalletAccountMutation(c.config, OpUpdateOne, withDriverWalletAccount(_m))
	return &DriverWalletAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DriverWalletAccountClient) UpdateOneID(id int) *DriverWalletAccountUpdateOne {
	mutation := newDriverWalletAccountMutation(c.config, OpUpdateOne, withDriverWalletAccountID(id))
	return &DriverWalletAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DriverWalletAccount.
func (c *DriverWalletAccountClient) Delete() *DriverWalletAccountDelete {
	mutation := newDriverWalletAccountMutation(c.config, OpDelete)
	return &DriverWalletAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DriverWalletAccountClient) DeleteOne(_m *DriverWalletAccount) *DriverWalletAccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DriverWalletAccountClient) DeleteOneID(id int) *DriverWalletAccountDeleteOne {
	builder := c.Delete().Where(driverwalletaccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DriverWalletAccountDeleteOne{builder}
}

// Query returns a query builder for DriverWalletAccount.
func (c *DriverWalletAccountClient) Query() *DriverWalletAccountQuery {
	return &DriverWalletAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDriverWalletAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a DriverWalletAccount entity by its id.
func (c *DriverWalletAccountClient) Get(ctx context.Context, id int) (*DriverWalletAccount, error) {
	return c.Query().Where(driverwalletaccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DriverWalletAccountClient) GetX(ctx context.Context, id int) *DriverWalletAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DriverWalletAccountClient) Hooks() []Hook {
	return c.hooks.DriverWalletAccount
}

// Interceptors returns the client interceptors.
func (c *DriverWalletAccountClient) Interceptors() []Interceptor {
	return c.inters.DriverWalletAccount
}

func (c *DriverWalletAccountClient) mutate(ctx context.Context, m *DriverWalletAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DriverWalletAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DriverWalletAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DriverWalletAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DriverWalletAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DriverWalletAccount mutation op: %q", m.Op())
	}
}

// NotificationClient is a client for the Notification schema.
type NotificationClient struct {
	config
}

// NewNotificationClient returns a client for the Notification from the given config.
func NewNotificationClient(c config) *NotificationClient {
	return &NotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notification.Hooks(f(g(h())))`.
func (c *NotificationClient) Use(hooks ...Hook) {
	c.hooks.Notification = append(c.hooks.Notification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notification.Intercept(f(g(h())))`.
func (c *NotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Notification = append(c.inters.Notification, interceptors...)
}

// Create returns a builder for creating a Notification entity.
func (c *NotificationClient) Create() *NotificationCreate {
	mutation := newNotificationMutation(c.config, OpCreate)
	return &NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Notification entities.
func (c *NotificationClient) CreateBulk(builders ...*NotificationCreate) *NotificationCreateBulk {
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationClient) MapCreateBulk(slice any, setFunc func(*NotificationCreate, int)) *NotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationCreateBulk{err: fmt.Errorf("calling to NotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notification.
func (c *NotificationClient) Update() *NotificationUpdate {
	mutation := newNotificationMutation(c.config, OpUpdate)
	return &NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationClient) UpdateOne(_m *Notification) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotification(_m))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationClient) UpdateOneID(id int) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotificationID(id))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notification.
func (c *NotificationClient) Delete() *NotificationDelete {
	mutation := newNotificationMutation(c.config, OpDelete)
	return &NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationClient) DeleteOne(_m *Notification) *NotificationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationClient) DeleteOneID(id int) *NotificationDeleteOne {
	builder := c.Delete().Where(notification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationDeleteOne{builder}
}

// Query returns a query builder for Notification.
func (c *NotificationClient) Query() *NotificationQuery {
	return &NotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a Notification entity by its id.
func (c *NotificationClient) Get(ctx context.Context, id int) (*Notification, error) {
	return c.Query().Where(notification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationClient) GetX(ctx context.Context, id int) *Notification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotificationClient) Hooks() []Hook {
	return c.hooks.Notification
}

// Interceptors returns the client interceptors.
func (c *NotificationClient) Interceptors() []Interceptor {
	return c.inters.Notification
}

func (c *NotificationClient) mutate(ctx context.Context, m *NotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Notification mutation op: %q", m.Op())
	}
}

// PassengerProfileClient is a client for the PassengerProfile schema.
type PassengerProfileClient struct {
	config
}

// NewPassengerProfileClient returns a client for the PassengerProfile from the given config.
func NewPassengerProfileClient(c config) *PassengerProfileClient {
	return &PassengerProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passengerprofile.Hooks(f(g(h())))`.
func (c *PassengerProfileClient) Use(hooks ...Hook) {
	c.hooks.PassengerProfile = append(c.hooks.PassengerProfile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passengerprofile.Intercept(f(g(h())))`.
func (c *PassengerProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.PassengerProfile = append(c.inters.PassengerProfile, interceptors...)
}

// Create returns a builder for creating a PassengerProfile entity.
func (c *PassengerProfileClient) Create() *PassengerProfileCreate {
	mutation := newPassengerProfileMutation(c.config, OpCreate)
	return &PassengerProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PassengerProfile entities.
func (c *PassengerProfileClient) CreateBulk(builders ...*PassengerProfileCreate) *PassengerProfileCreateBulk {
	return &PassengerProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PassengerProfileClient) MapCreateBulk(slice any, setFunc func(*PassengerProfileCreate, int)) *PassengerProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PassengerProfileCreateBulk{err: fmt.Errorf("calling to PassengerProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PassengerProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PassengerProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PassengerProfile.
func (c *PassengerProfileClient) Update() *PassengerProfileUpdate {
	mutation := newPassengerProfileMutation(c.config, OpUpdate)
	return &PassengerProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PassengerProfileClient) UpdateOne(_m *PassengerProfile) *PassengerProfileUpdateOne {
	mutation := newPassengerProfileMutation(c.config, OpUpdateOne, withPassengerProfile(_m))
	return &PassengerProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PassengerProfileClient) UpdateOneID(id int) *PassengerProfileUpdateOne {
	mutation := newPassengerProfileMutation(c.config, OpUpdateOne, withPassengerProfileID(id))
	return &PassengerProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PassengerProfile.
func (c *PassengerProfileClient) Delete() *PassengerProfileDelete {
	mutation := newPassengerProfileMutation(c.config, OpDelete)
	return &PassengerProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PassengerProfileClient) DeleteOne(_m *PassengerProfile) *PassengerProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PassengerProfileClient) DeleteOneID(id int) *PassengerProfileDeleteOne {
	builder := c.Delete().Where(passengerprofile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PassengerProfileDeleteOne{builder}
}

// Query returns a query builder for PassengerProfile.
func (c *PassengerProfileClient) Query() *PassengerProfileQuery {
	return &PassengerProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePassengerProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a PassengerProfile entity by its id.
func (c *PassengerProfileClient) Get(ctx context.Context, id int) (*PassengerProfile, error) {
	return c.Query().Where(passengerprofile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PassengerProfileClient) GetX(ctx context.Context, id int) *PassengerProfile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PassengerProfileClient) Hooks() []Hook {
	return c.hooks.PassengerProfile
}

// Interceptors returns the client interceptors.
func (c *PassengerProfileClient) Interceptors() []Interceptor {
	return c.inters.PassengerProfile
}

func (c *PassengerProfileClient) mutate(ctx context.Context, m *PassengerProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PassengerProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PassengerProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PassengerProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PassengerProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PassengerProfile mutation op: %q", m.Op())
	}
}

// PassengerReviewClient is a client for the PassengerReview schema.
type PassengerReviewClient struct {
	config
}

// NewPassengerReviewClient returns a client for the PassengerReview from the given config.
func NewPassengerReviewClient(c config) *PassengerReviewClient {
	return &PassengerReviewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passengerreview.Hooks(f(g(h())))`.
func (c *PassengerReviewClient) Use(hooks ...Hook) {
	c.hooks.PassengerReview = append(c.hooks.PassengerReview, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passengerreview.Intercept(f(g(h())))`.
func (c *PassengerReviewClient) Intercept(interceptors ...Interceptor) {
	c.inters.PassengerReview = append(c.inters.PassengerReview, interceptors...)
}

// Create returns a builder for creating a PassengerReview entity.
func (c *PassengerReviewClient) Create() *PassengerReviewCreate {
	mutation := newPassengerReviewMutation(c.config, OpCreate)
	return &PassengerReviewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PassengerReview entities.
func (c *PassengerReviewClient) CreateBulk(builders ...*PassengerReviewCreate) *PassengerReviewCreateBulk {
	return &PassengerReviewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PassengerReviewClient) MapCreateBulk(slice any, setFunc func(*PassengerReviewCreate, int)) *PassengerReviewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PassengerReviewCreateBulk{err: fmt.Errorf("calling to PassengerReviewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PassengerReviewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PassengerReviewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PassengerReview.
func (c *PassengerReviewClient) Update() *PassengerReviewUpdate {
	mutation := newPassengerReviewMutation(c.config, OpUpdate)
	return &PassengerReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PassengerReviewClient) UpdateOne(_m *PassengerReview) *PassengerReviewUpdateOne {
	mutation := newPassengerReviewMutation(c.config, OpUpdateOne, withPassengerReview(_m))
	return &PassengerReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PassengerReviewClient) UpdateOneID(id int) *PassengerReviewUpdateOne {
	mutation := newPassengerReviewMutation(c.config, OpUpdateOne, withPassengerReviewID(id))
	return &PassengerReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PassengerReview.
func (c *PassengerReviewClient) Delete() *PassengerReviewDelete {
	mutation := newPassengerReviewMutation(c.config, OpDelete)
	return &PassengerReviewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PassengerReviewClient) DeleteOne(_m *PassengerReview) *PassengerReviewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PassengerReviewClient) DeleteOneID(id int) *PassengerReviewDeleteOne {
	builder := c.Delete().Where(passengerreview.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PassengerReviewDeleteOne{builder}
}

// Query returns a query builder for PassengerReview.
func (c *PassengerReviewClient) Query() *PassengerReviewQuery {
	return &PassengerReviewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePassengerReview},
		inters: c.Interceptors(),
	}
}

// Get returns a PassengerReview entity by its id.
func (c *PassengerReviewClient) Get(ctx context.Context, id int) (*PassengerReview, error) {
	return c.Query().Where(passengerreview.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PassengerReviewClient) GetX(ctx context.Context, id int) *PassengerReview {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PassengerReviewClient) Hooks() []Hook {
	return c.hooks.PassengerReview
}

// Interceptors returns the client interceptors.
func (c *PassengerReviewClient) Interceptors() []Interceptor {
	return c.inters.PassengerReview
}

func (c *PassengerReviewClient) mutate(ctx context.Context, m *PassengerReviewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PassengerReviewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PassengerReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PassengerReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PassengerReviewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PassengerReview mutation op: %q", m.Op())
	}
}

// PrivateObjectClient is a client for the PrivateObject schema.
type PrivateObjectClient struct {
	config
}

// NewPrivateObjectClient returns a client for the PrivateObject from the given config.
func NewPrivateObjectClient(c config) *PrivateObjectClient {
	return &PrivateObjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `privateobject.Hooks(f(g(h())))`.
func (c *PrivateObjectClient) Use(hooks ...Hook) {
	c.hooks.PrivateObject = append(c.hooks.PrivateObject, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `privateobject.Intercept(f(g(h())))`.
func (c *PrivateObjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.PrivateObject = append(c.inters.PrivateObject, interceptors...)
}

// Create returns a builder for creating a PrivateObject entity.
func (c *PrivateObjectClient) Create() *PrivateObjectCreate {
	mutation := newPrivateObjectMutation(c.config, OpCreate)
	return &PrivateObjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PrivateObject entities.
func (c *PrivateObjectClient) CreateBulk(builders ...*PrivateObjectCreate) *PrivateObjectCreateBulk {
	return &PrivateObjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PrivateObjectClient) MapCreateBulk(slice any, setFunc func(*PrivateObjectCreate, int)) *PrivateObjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PrivateObjectCreateBulk{err: fmt.Errorf("calling to PrivateObjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PrivateObjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PrivateObjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PrivateObject.
func (c *PrivateObjectClient) Update() *PrivateObjectUpdate {
	mutation := newPrivateObjectMutation(c.config, OpUpdate)
	return &PrivateObjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PrivateObjectClient) UpdateOne(_m *PrivateObject) *PrivateObjectUpdateOne {
	mutation := newPrivateObjectMutation(c.config, OpUpdateOne, withPrivateObject(_m))
	return &PrivateObjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PrivateObjectClient) UpdateOneID(id int) *PrivateObjectUpdateOne {
	mutation := newPrivateObjectMutation(c.config, OpUpdateOne, withPrivateObjectID(id))
	return &PrivateObjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PrivateObject.
func (c *PrivateObjectClient) Delete() *PrivateObjectDelete {
	mutation := newPrivateObjectMutation(c.config, OpDelete)
	return &PrivateObjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PrivateObjectClient) DeleteOne(_m *PrivateObject) *PrivateObjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PrivateObjectClient) DeleteOneID(id int) *PrivateObjectDeleteOne {
	builder := c.Delete().Where(privateobject.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PrivateObjectDeleteOne{builder}
}

// Query returns a query builder for PrivateObject.
func (c *PrivateObjectClient) Query() *PrivateObjectQuery {
	return &PrivateObjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePrivateObject},
		inters: c.Interceptors(),
	}
}

// Get returns a PrivateObject entity by its id.
func (c *PrivateObjectClient) Get(ctx context.Context, id int) (*PrivateObject, error) {
	return c.Query().Where(privateobject.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PrivateObjectClient) GetX(ctx context.Context, id int) *PrivateObject {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PrivateObjectClient) Hooks() []Hook {
	return c.hooks.PrivateObject
}

// Interceptors returns the client interceptors.
func (c *PrivateObjectClient) Interceptors() []Interceptor {
	return c.inters.PrivateObject
}

func (c *PrivateObjectClient) mutate(ctx context.Context, m *PrivateObjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PrivateObjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PrivateObjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PrivateObjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PrivateObjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PrivateObject mutation op: %q", m.Op())
	}
}

// RefreshSessionClient is a client for the RefreshSession schema.
type RefreshSessionClient struct {
	config
}

// NewRefreshSessionClient returns a client for the RefreshSession from the given config.
func NewRefreshSessionClient(c config) *RefreshSessionClient {
	return &RefreshSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refreshsession.Hooks(f(g(h())))`.
func (c *RefreshSessionClient) Use(hooks ...Hook) {
	c.hooks.RefreshSession = append(c.hooks.RefreshSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refreshsession.Intercept(f(g(h())))`.
func (c *RefreshSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefreshSession = append(c.inters.RefreshSession, interceptors...)
}

// Create returns a builder for creating a RefreshSession entity.
func (c *RefreshSessionClient) Create() *RefreshSessionCreate {
	mutation := newRefreshSessionMutation(c.config, OpCreate)
	return &RefreshSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefreshSession entities.
func (c *RefreshSessionClient) CreateBulk(builders ...*RefreshSessionCreate) *RefreshSessionCreateBulk {
	return &RefreshSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefreshSessionClient) MapCreateBulk(slice any, setFunc func(*RefreshSessionCreate, int)) *RefreshSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefreshSessionCreateBulk{err: fmt.Errorf("calling to RefreshSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefreshSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefreshSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefreshSession.
func (c *RefreshSessionClient) Update() *RefreshSessionUpdate {
	mutation := newRefreshSessionMutation(c.config, OpUpdate)
	return &RefreshSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefreshSessionClient) UpdateOne(_m *RefreshSession) *RefreshSessionUpdateOne {
	mutation := newRefreshSessionMutation(c.config, OpUpdateOne, withRefreshSession(_m))
	return &RefreshSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefreshSessionClient) UpdateOneID(id int) *RefreshSessionUpdateOne {
	mutation := newRefreshSessionMutation(c.config, OpUpdateOne, withRefreshSessionID(id))
	return &RefreshSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefreshSession.
func (c *RefreshSessionClient) Delete() *RefreshSessionDelete {
	mutation := newRefreshSessionMutation(c.config, OpDelete)
	return &RefreshSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefreshSessionClient) DeleteOne(_m *RefreshSession) *RefreshSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefreshSessionClient) DeleteOneID(id int) *RefreshSessionDeleteOne {
	builder := c.Delete().Where(refreshsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefreshSessionDeleteOne{builder}
}

// Query returns a query builder for RefreshSession.
func (c *RefreshSessionClient) Query() *RefreshSessionQuery {
	return &RefreshSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefreshSession},
		inters: c.Interceptors(),
	}
}

// Get returns a RefreshSession entity by its id.
func (c *RefreshSessionClient) Get(ctx context.Context, id int) (*RefreshSession, error) {
	return c.Query().Where(refreshsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefreshSessionClient) GetX(ctx context.Context, id int) *RefreshSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RefreshSessionClient) Hooks() []Hook {
	return c.hooks.RefreshSession
}

// Interceptors returns the client interceptors.
func (c *RefreshSessionClient) Interceptors() []Interceptor {
	return c.inters.RefreshSession
}

func (c *RefreshSessionClient) mutate(ctx context.Context, m *RefreshSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefreshSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefreshSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefreshSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefreshSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefreshSession mutation op: %q", m.Op())
	}
}

// ReviewClient is a client for the Review schema.
type ReviewClient struct {
	config
}

// NewReviewClient returns a client for the Review from the given config.
func NewReviewClient(c config) *ReviewClient {
	return &ReviewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `review.Hooks(f(g(h())))`.
func (c *ReviewClient) Use(hooks ...Hook) {
	c.hooks.Review = append(c.hooks.Review, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `review.Intercept(f(g(h())))`.
func (c *ReviewClient) Intercept(interceptors ...Interceptor) {
	c.inters.Review = append(c.inters.Review, interceptors...)
}

// Create returns a builder for creating a Review entity.
func (c *ReviewClient) Create() *ReviewCreate {
	mutation := newReviewMutation(c.config, OpCreate)
	return &ReviewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Review entities.
func (c *ReviewClient) CreateBulk(builders ...*ReviewCreate) *ReviewCreateBulk {
	return &ReviewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReviewClient) MapCreateBulk(slice any, setFunc func(*ReviewCreate, int)) *ReviewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReviewCreateBulk{err: fmt.Errorf("calling to ReviewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReviewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReviewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Review.
func (c *ReviewClient) Update() *ReviewUpdate {
	mutation := newReviewMutation(c.config, OpUpdate)
	return &ReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReviewClient) UpdateOne(_m *Review) *ReviewUpdateOne {
	mutation := newReviewMutation(c.config, OpUpdateOne, withReview(_m))
	return &ReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReviewClient) UpdateOneID(id int) *ReviewUpdateOne {
	mutation := newReviewMutation(c.config, OpUpdateOne, withReviewID(id))
	return &ReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Review.
func (c *ReviewClient) Delete() *ReviewDelete {
	mutation := newReviewMutation(c.config, OpDelete)
	return &ReviewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReviewClient) DeleteOne(_m *Review) *ReviewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReviewClient) DeleteOneID(id int) *ReviewDeleteOne {
	builder := c.Delete().Where(review.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReviewDeleteOne{builder}
}

// Query returns a query builder for Review.
func (c *ReviewClient) Query() *ReviewQuery {
	return &ReviewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReview},
		inters: c.Interceptors(),
	}
}

// Get returns a Review entity by its id.
func (c *ReviewClient) Get(ctx context.Context, id int) (*Review, error) {
	return c.Query().Where(review.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReviewClient) GetX(ctx context.Context, id int) *Review {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ReviewClient) Hooks() []Hook {
	return c.hooks.Review
}

// Interceptors returns the client interceptors.
func (c *ReviewClient) Interceptors() []Interceptor {
	return c.inters.Review
}

func (c *ReviewClient) mutate(ctx context.Context, m *ReviewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReviewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReviewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Review mutation op: %q", m.Op())
	}
}

// RideClient is a client for the Ride schema.
type RideClient struct {
	config
}

// NewRideClient returns a client for the Ride from the given config.
func NewRideClient(c config) *RideClient {
	return &RideClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ride.Hooks(f(g(h())))`.
func (c *RideClient) Use(hooks ...Hook) {
	c.hooks.Ride = append(c.hooks.Ride, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ride.Intercept(f(g(h())))`.
func (c *RideClient) Intercept(interceptors ...Interceptor) {
	c.inters.Ride = append(c.inters.Ride, interceptors...)
}

// Create returns a builder for creating a Ride entity.
func (c *RideClient) Create() *RideCreate {
	mutation := newRideMutation(c.config, OpCreate)
	return &RideCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Ride entities.
func (c *RideClient) CreateBulk(builders ...*RideCreate) *RideCreateBulk {
	return &RideCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RideClient) MapCreateBulk(slice any, setFunc func(*RideCreate, int)) *RideCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RideCreateBulk{err: fmt.Errorf("calling to RideClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RideCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RideCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Ride.
func (c *RideClient) Update() *RideUpdate {
	mutation := newRideMutation(c.config, OpUpdate)
	return &RideUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RideClient) UpdateOne(_m *Ride) *RideUpdateOne {
	mutation := newRideMutation(c.config, OpUpdateOne, withRide(_m))
	return &RideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RideClient) UpdateOneID(id int) *RideUpdateOne {
	mutation := newRideMutation(c.config, OpUpdateOne, withRideID(id))
	return &RideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Ride.
func (c *RideClient) Delete() *RideDelete {
	mutation := newRideMutation(c.config, OpDelete)
	return &RideDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RideClient) DeleteOne(_m *Ride) *RideDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RideClient) DeleteOneID(id int) *RideDeleteOne {
	builder := c.Delete().Where(ride.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RideDeleteOne{builder}
}

// Query returns a query builder for Ride.
func (c *RideClient) Query() *RideQuery {
	return &RideQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRide},
		inters: c.Interceptors(),
	}
}

// Get returns a Ride entity by its id.
func (c *RideClient) Get(ctx context.Context, id int) (*Ride, error) {
	return c.Query().Where(ride.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RideClient) GetX(ctx context.Context, id int) *Ride {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RideClient) Hooks() []Hook {
	return c.hooks.Ride
}

// Interceptors returns the client interceptors.
func (c *RideClient) Interceptors() []Interceptor {
	return c.inters.Ride
}

func (c *RideClient) mutate(ctx context.Context, m *RideMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RideCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RideUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RideDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Ride mutation op: %q", m.Op())
	}
}

// RideSettlementClient is a client for the RideSettlement schema.
type RideSettlementClient struct {
	config
}

// NewRideSettlementClient returns a client for the RideSettlement from the given config.
func NewRideSettlementClient(c config) *RideSettlementClient {
	return &RideSettlementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ridesettlement.Hooks(f(g(h())))`.
func (c *RideSettlementClient) Use(hooks ...Hook) {
	c.hooks.RideSettlement = append(c.hooks.RideSettlement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ridesettlement.Intercept(f(g(h())))`.
func (c *RideSettlementClient) Intercept(interceptors ...Interceptor) {
	c.inters.RideSettlement = append(c.inters.RideSettlement, interceptors...)
}

// Create returns a builder for creating a RideSettlement entity.
func (c *RideSettlementClient) Create() *RideSettlementCreate {
	mutation := newRideSettlementMutation(c.config, OpCreate)
	return &RideSettlementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RideSettlement entities.
func (c *RideSettlementClient) CreateBulk(builders ...*RideSettlementCreate) *RideSettlementCreateBulk {
	return &RideSettlementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RideSettlementClient) MapCreateBulk(slice any, setFunc func(*RideSettlementCreate, int)) *RideSettlementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RideSettlementCreateBulk{err: fmt.Errorf("calling to RideSettlementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RideSettlementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RideSettlementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RideSettlement.
func (c *RideSettlementClient) Update() *RideSettlementUpdate {
	mutation := newRideSettlementMutation(c.config, OpUpdate)
	return &RideSettlementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RideSettlementClient) UpdateOne(_m *RideSettlement) *RideSettlementUpdateOne {
	mutation := newRideSettlementMutation(c.config, OpUpdateOne, withRideSettlement(_m))
	return &RideSettlementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RideSettlementClient) UpdateOneID(id int) *RideSettlementUpdateOne {
	mutation := newRideSettlementMutation(c.config, OpUpdateOne, withRideSettlementID(id))
	return &RideSettlementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RideSettlement.
func (c *RideSettlementClient) Delete() *RideSettlementDelete {
	mutation := newRideSettlementMutation(c.config, OpDelete)
	return &RideSettlementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RideSettlementClient) DeleteOne(_m *RideSettlement) *RideSettlementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RideSettlementClient) DeleteOneID(id int) *RideSettlementDeleteOne {
	builder := c.Delete().Where(ridesettlement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RideSettlementDeleteOne{builder}
}

// Query returns a query builder for RideSettlement.
func (c *RideSettlementClient) Query() *RideSettlementQuery {
	return &RideSettlementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRideSettlement},
		inters: c.Interceptors(),
	}
}

// Get returns a RideSettlement entity by its id.
func (c *RideSettlementClient) Get(ctx context.Context, id int) (*RideSettlement, error) {
	return c.Query().Where(ridesettlement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RideSettlementClient) GetX(ctx context.Context, id int) *RideSettlement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RideSettlementClient) Hooks() []Hook {
	return c.hooks.RideSettlement
}

// Interceptors returns the client interceptors.
func (c *RideSettlementClient) Interceptors() []Interceptor {
	return c.inters.RideSettlement
}

func (c *RideSettlementClient) mutate(ctx context.Context, m *RideSettlementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RideSettlementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RideSettlementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RideSettlementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RideSettlementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RideSettlement mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// WalletLedgerClient is a client for the WalletLedger schema.
type WalletLedgerClient struct {
	config
}

// NewWalletLedgerClient returns a client for the WalletLedger from the given config.
func NewWalletLedgerClient(c config) *WalletLedgerClient {
	return &WalletLedgerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `walletledger.Hooks(f(g(h())))`.
func (c *WalletLedgerClient) Use(hooks ...Hook) {
	c.hooks.WalletLedger = append(c.hooks.WalletLedger, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `walletledger.Intercept(f(g(h())))`.
func (c *WalletLedgerClient) Intercept(interceptors ...Interceptor) {
	c.inters.WalletLedger = append(c.inters.WalletLedger, interceptors...)
}

// Create returns a builder for creating a WalletLedger entity.
func (c *WalletLedgerClient) Create() *WalletLedgerCreate {
	mutation := newWalletLedgerMutation(c.config, OpCreate)
	return &WalletLedgerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WalletLedger entities.
func (c *WalletLedgerClient) CreateBulk(builders ...*WalletLedgerCreate) *WalletLedgerCreateBulk {
	return &WalletLedgerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WalletLedgerClient) MapCreateBulk(slice any, setFunc func(*WalletLedgerCreate, int)) *WalletLedgerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WalletLedgerCreateBulk{err: fmt.Errorf("calling to WalletLedgerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WalletLedgerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WalletLedgerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WalletLedger.
func (c *WalletLedgerClient) Update() *WalletLedgerUpdate {
	mutation := newWalletLedgerMutation(c.config, OpUpdate)
	return &WalletLedgerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WalletLedgerClient) UpdateOne(_m *WalletLedger) *WalletLedgerUpdateOne {
	mutation := newWalletLedgerMutation(c.config, OpUpdateOne, withWalletLedger(_m))
	return &WalletLedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WalletLedgerClient) UpdateOneID(id int) *WalletLedgerUpdateOne {
	mutation := newWalletLedgerMutation(c.config, OpUpdateOne, withWalletLedgerID(id))
	return &WalletLedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WalletLedger.
func (c *WalletLedgerClient) Delete() *WalletLedgerDelete {
	mutation := newWalletLedgerMutation(c.config, OpDelete)
	return &WalletLedgerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WalletLedgerClient) DeleteOne(_m *WalletLedger) *WalletLedgerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WalletLedgerClient) DeleteOneID(id int) *WalletLedgerDeleteOne {
	builder := c.Delete().Where(walletledger.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WalletLedgerDeleteOne{builder}
}

// Query returns a query builder for WalletLedger.
func (c *WalletLedgerClient) Query() *WalletLedgerQuery {
	return &WalletLedgerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWalletLedger},
		inters: c.Interceptors(),
	}
}

// Get returns a WalletLedger entity by its id.
func (c *WalletLedgerClient) Get(ctx context.Context, id int) (*WalletLedger, error) {
	return c.Query().Where(walletledger.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WalletLedgerClient) GetX(ctx context.Context, id int) *WalletLedger {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WalletLedgerClient) Hooks() []Hook {
	return c.hooks.WalletLedger
}

// Interceptors returns the client interceptors.
func (c *WalletLedgerClient) Interceptors() []Interceptor {
	return c.inters.WalletLedger
}

func (c *WalletLedgerClient) mutate(ctx context.Context, m *WalletLedgerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WalletLedgerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WalletLedgerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WalletLedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WalletLedgerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WalletLedger mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AuditEvent, Bid, BidOffer, BidSession, DriverDocument, DriverProfile,
		DriverWalletAccount, Notification, PassengerProfile, PassengerReview,
		PrivateObject, RefreshSession, Review, Ride, RideSettlement, User,
		WalletLedger []ent.Hook
	}
	inters struct {
		AuditEvent, Bid, BidOffer, BidSession, DriverDocument, DriverProfile,
		DriverWalletAccount, Notification, PassengerProfile, PassengerReview,
		PrivateObject, RefreshSession, Review, Ride, RideSettlement, User,
		WalletLedger []ent.Interceptor
	}
)
