// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverprofile"
)

// DriverProfile is the model entity for the DriverProfile schema.
type DriverProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// VehicleType holds the value of the "vehicle_type" field.
	VehicleType string `json:"vehicle_type,omitempty"`
	// PlateNumber holds the value of the "plate_number" field.
	PlateNumber string `json:"plate_number,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating float64 `json:"rating,omitempty"`
	// IsOnline holds the value of the "is_online" field.
	IsOnline bool `json:"is_online,omitempty"`
	// WalletBalanceCentavos holds the value of the "wallet_balance_centavos" field.
	WalletBalanceCentavos int64 `json:"wallet_balance_centavos,omitempty"`
	selectValues          sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DriverProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case driverprofile.FieldIsOnline:
			values[i] = new(sql.NullBool)
		case driverprofile.FieldRating:
			values[i] = new(sql.NullFloat64)
		case driverprofile.FieldID, driverprofile.FieldUserID, driverprofile.FieldWalletBalanceCentavos:
			values[i] = new(sql.NullInt64)
		case driverprofile.FieldName, driverprofile.FieldVehicleType, driverprofile.FieldPlateNumber:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DriverProfile fields.
func (_m *DriverProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case driverprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case driverprofile.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case driverprofile.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case driverprofile.FieldVehicleType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vehicle_type", values[i])
			} else if value.Valid {
				_m.VehicleType = value.String
			}
		case driverprofile.FieldPlateNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plate_number", values[i])
			} else if value.Valid {
				_m.PlateNumber = value.String
			}
		case driverprofile.FieldRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = value.Float64
			}
		case driverprofile.FieldIsOnline:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_online", values[i])
			} else if value.Valid {
				_m.IsOnline = value.Bool
			}
		case driverprofile.FieldWalletBalanceCentavos:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_balance_centavos", values[i])
			} else if value.Valid {
				_m.WalletBalanceCentavos = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DriverProfile.
// This includes values selected through modifiers, order, etc.
func (_m *DriverProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DriverProfile.
// Note that you need to call DriverProfile.Unwrap() before calling this method if this DriverProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DriverProfile) Update() *DriverProfileUpdateOne {
	return NewDriverProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DriverProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DriverProfile) Unwrap() *DriverProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DriverProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DriverProfile) String() string {
	var builder strings.Builder
	builder.WriteString("DriverProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("vehicle_type=")
	builder.WriteString(_m.VehicleType)
	builder.WriteString(", ")
	builder.WriteString("plate_number=")
	builder.WriteString(_m.PlateNumber)
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("is_online=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOnline))
	builder.WriteString(", ")
	builder.WriteString("wallet_balance_centavos=")
	builder.WriteString(fmt.Sprintf("%v", _m.WalletBalanceCentavos))
	builder.WriteByte(')')
	return builder.String()
}

// DriverProfiles is a parsable slice of DriverProfile.
type DriverProfiles []*DriverProfile
