// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverwalletaccount"
)

// DriverWalletAccountCreate is the builder for creating a DriverWalletAccount entity.
type DriverWalletAccountCreate struct {
	config
	mutation *DriverWalletAccountMutation
	hooks    []Hook
}

// SetDriverID sets the "driver_id" field.
func (_c *DriverWalletAccountCreate) SetDriverID(v int) *DriverWalletAccountCreate {
	_c.mutation.SetDriverID(v)
	return _c
}

// SetBalanceCentavos sets the "balance_centavos" field.
func (_c *DriverWalletAccountCreate) SetBalanceCentavos(v int64) *DriverWalletAccountCreate {
	_c.mutation.SetBalanceCentavos(v)
	return _c
}

// SetNillableBalanceCentavos sets the "balance_centavos" field if the given value is not nil.
func (_c *DriverWalletAccountCreate) SetNillableBalanceCentavos(v *int64) *DriverWalletAccountCreate {
	if v != nil {
		_c.SetBalanceCentavos(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *DriverWalletAccountCreate) SetVersion(v int64) *DriverWalletAccountCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *DriverWalletAccountCreate) SetNillableVersion(v *int64) *DriverWalletAccountCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DriverWalletAccountCreate) SetUpdatedAt(v time.Time) *DriverWalletAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DriverWalletAccountCreate) SetNillableUpdatedAt(v *time.Time) *DriverWalletAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DriverWalletAccountMutation object of the builder.
func (_c *DriverWalletAccountCreate) Mutation() *DriverWalletAccountMutation {
	return _c.mutation
}

// Save creates the DriverWalletAccount in the database.
func (_c *DriverWalletAccountCreate) Save(ctx context.Context) (*DriverWalletAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DriverWalletAccountCreate) SaveX(ctx context.Context) *DriverWalletAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriverWalletAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriverWalletAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DriverWalletAccountCreate) defaults() {
	if _, ok := _c.mutation.BalanceCentavos(); !ok {
		v := driverwalletaccount.DefaultBalanceCentavos
		_c.mutation.SetBalanceCentavos(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := driverwalletaccount.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := driverwalletaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DriverWalletAccountCreate) check() error {
	if _, ok := _c.mutation.DriverID(); !ok {
		return &ValidationError{Name: "driver_id", err: errors.New(`ent: missing required field "DriverWalletAccount.driver_id"`)}
	}
	if v, ok := _c.mutation.DriverID(); ok {
		if err := driverwalletaccount.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "DriverWalletAccount.driver_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceCentavos(); !ok {
		return &ValidationError{Name: "balance_centavos", err: errors.New(`ent: missing required field "DriverWalletAccount.balance_centavos"`)}
	}
	if v, ok := _c.mutation.BalanceCentavos(); ok {
		if err := driverwalletaccount.BalanceCentavosValidator(v); err != nil {
			return &ValidationError{Name: "balance_centavos", err: fmt.Errorf(`ent: validator failed for field "DriverWalletAccount.balance_centavos": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DriverWalletAccount.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := driverwalletaccount.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DriverWalletAccount.version": %w`, err)}
		}
	}
	return nil
}

func (_c *DriverWalletAccountCreate) sqlSave(ctx context.Context) (*DriverWalletAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DriverWalletAccountCreate) createSpec() (*DriverWalletAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &DriverWalletAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(driverwalletaccount.Table, sqlgraph.NewFieldSpec(driverwalletaccount.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DriverID(); ok {
		_spec.SetField(driverwalletaccount.FieldDriverID, field.TypeInt, value)
		_node.DriverID = value
	}
	if value, ok := _c.mutation.BalanceCentavos(); ok {
		_spec.SetField(driverwalletaccount.FieldBalanceCentavos, field.TypeInt64, value)
		_node.BalanceCentavos = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(driverwalletaccount.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(driverwalletaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DriverWalletAccountCreateBulk is the builder for creating many DriverWalletAccount entities in bulk.
type DriverWalletAccountCreateBulk struct {
	config
	err      error
	builders []*DriverWalletAccountCreate
}

// Save creates the DriverWalletAccount entities in the database.
func (_c *DriverWalletAccountCreateBulk) Save(ctx context.Context) ([]*DriverWalletAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DriverWalletAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DriverWalletAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DriverWalletAccountCreateBulk) SaveX(ctx context.Context) []*DriverWalletAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriverWalletAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriverWalletAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
