// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverwalletaccount"
	"github.com/Easy-Bao/DrivingApp/server/ent/predicate"
)

// DriverWalletAccountDelete is the builder for deleting a DriverWalletAccount entity.
type DriverWalletAccountDelete struct {
	config
	hooks    []Hook
	mutation *DriverWalletAccountMutation
}

// Where appends a list predicates to the DriverWalletAccountDelete builder.
func (_d *DriverWalletAccountDelete) Where(ps ...predicate.DriverWalletAccount) *DriverWalletAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DriverWalletAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DriverWalletAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DriverWalletAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(driverwalletaccount.Table, sqlgraph.NewFieldSpec(driverwalletaccount.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DriverWalletAccountDeleteOne is the builder for deleting a single DriverWalletAccount entity.
type DriverWalletAccountDeleteOne struct {
	_d *DriverWalletAccountDelete
}

// Where appends a list predicates to the DriverWalletAccountDelete builder.
func (_d *DriverWalletAccountDeleteOne) Where(ps ...predicate.DriverWalletAccount) *DriverWalletAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DriverWalletAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{driverwalletaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DriverWalletAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
