// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverprofile"
	"github.com/Easy-Bao/DrivingApp/server/ent/predicate"
)

// DriverProfileUpdate is the builder for updating DriverProfile entities.
type DriverProfileUpdate struct {
	config
	hooks    []Hook
	mutation *DriverProfileMutation
}

// Where appends a list predicates to the DriverProfileUpdate builder.
func (_u *DriverProfileUpdate) Where(ps ...predicate.DriverProfile) *DriverProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DriverProfileUpdate) SetUserID(v int) *DriverProfileUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillableUserID(v *int) *DriverProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DriverProfileUpdate) AddUserID(v int) *DriverProfileUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DriverProfileUpdate) SetName(v string) *DriverProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillableName(v *string) *DriverProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVehicleType sets the "vehicle_type" field.
func (_u *DriverProfileUpdate) SetVehicleType(v string) *DriverProfileUpdate {
	_u.mutation.SetVehicleType(v)
	return _u
}

// SetNillableVehicleType sets the "vehicle_type" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillableVehicleType(v *string) *DriverProfileUpdate {
	if v != nil {
		_u.SetVehicleType(*v)
	}
	return _u
}

// SetPlateNumber sets the "plate_number" field.
func (_u *DriverProfileUpdate) SetPlateNumber(v string) *DriverProfileUpdate {
	_u.mutation.SetPlateNumber(v)
	return _u
}

// SetNillablePlateNumber sets the "plate_number" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillablePlateNumber(v *string) *DriverProfileUpdate {
	if v != nil {
		_u.SetPlateNumber(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *DriverProfileUpdate) SetRating(v float64) *DriverProfileUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillableRating(v *float64) *DriverProfileUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *DriverProfileUpdate) AddRating(v float64) *DriverProfileUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetIsOnline sets the "is_online" field.
func (_u *DriverProfileUpdate) SetIsOnline(v bool) *DriverProfileUpdate {
	_u.mutation.SetIsOnline(v)
	return _u
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillableIsOnline(v *bool) *DriverProfileUpdate {
	if v != nil {
		_u.SetIsOnline(*v)
	}
	return _u
}

// SetWalletBalanceCentavos sets the "wallet_balance_centavos" field.
func (_u *DriverProfileUpdate) SetWalletBalanceCentavos(v int64) *DriverProfileUpdate {
	_u.mutation.ResetWalletBalanceCentavos()
	_u.mutation.SetWalletBalanceCentavos(v)
	return _u
}

// SetNillableWalletBalanceCentavos sets the "wallet_balance_centavos" field if the given value is not nil.
func (_u *DriverProfileUpdate) SetNillableWalletBalanceCentavos(v *int64) *DriverProfileUpdate {
	if v != nil {
		_u.SetWalletBalanceCentavos(*v)
	}
	return _u
}

// AddWalletBalanceCentavos adds value to the "wallet_balance_centavos" field.
func (_u *DriverProfileUpdate) AddWalletBalanceCentavos(v int64) *DriverProfileUpdate {
	_u.mutation.AddWalletBalanceCentavos(v)
	return _u
}

// Mutation returns the DriverProfileMutation object of the builder.
func (_u *DriverProfileUpdate) Mutation() *DriverProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DriverProfileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DriverProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DriverProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DriverProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DriverProfileUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := driverprofile.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "DriverProfile.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletBalanceCentavos(); ok {
		if err := driverprofile.WalletBalanceCentavosValidator(v); err != nil {
			return &ValidationError{Name: "wallet_balance_centavos", err: fmt.Errorf(`ent: validator failed for field "DriverProfile.wallet_balance_centavos": %w`, err)}
		}
	}
	return nil
}

func (_u *DriverProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(driverprofile.Table, driverprofile.Columns, sqlgraph.NewFieldSpec(driverprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(driverprofile.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(driverprofile.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(driverprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.VehicleType(); ok {
		_spec.SetField(driverprofile.FieldVehicleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlateNumber(); ok {
		_spec.SetField(driverprofile.FieldPlateNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(driverprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(driverprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsOnline(); ok {
		_spec.SetField(driverprofile.FieldIsOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WalletBalanceCentavos(); ok {
		_spec.SetField(driverprofile.FieldWalletBalanceCentavos, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWalletBalanceCentavos(); ok {
		_spec.AddField(driverprofile.FieldWalletBalanceCentavos, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{driverprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DriverProfileUpdateOne is the builder for updating a single DriverProfile entity.
type DriverProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DriverProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *DriverProfileUpdateOne) SetUserID(v int) *DriverProfileUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillableUserID(v *int) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DriverProfileUpdateOne) AddUserID(v int) *DriverProfileUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DriverProfileUpdateOne) SetName(v string) *DriverProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillableName(v *string) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVehicleType sets the "vehicle_type" field.
func (_u *DriverProfileUpdateOne) SetVehicleType(v string) *DriverProfileUpdateOne {
	_u.mutation.SetVehicleType(v)
	return _u
}

// SetNillableVehicleType sets the "vehicle_type" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillableVehicleType(v *string) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetVehicleType(*v)
	}
	return _u
}

// SetPlateNumber sets the "plate_number" field.
func (_u *DriverProfileUpdateOne) SetPlateNumber(v string) *DriverProfileUpdateOne {
	_u.mutation.SetPlateNumber(v)
	return _u
}

// SetNillablePlateNumber sets the "plate_number" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillablePlateNumber(v *string) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetPlateNumber(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *DriverProfileUpdateOne) SetRating(v float64) *DriverProfileUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillableRating(v *float64) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *DriverProfileUpdateOne) AddRating(v float64) *DriverProfileUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetIsOnline sets the "is_online" field.
func (_u *DriverProfileUpdateOne) SetIsOnline(v bool) *DriverProfileUpdateOne {
	_u.mutation.SetIsOnline(v)
	return _u
}

// SetNillableIsOnline sets the "is_online" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillableIsOnline(v *bool) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetIsOnline(*v)
	}
	return _u
}

// SetWalletBalanceCentavos sets the "wallet_balance_centavos" field.
func (_u *DriverProfileUpdateOne) SetWalletBalanceCentavos(v int64) *DriverProfileUpdateOne {
	_u.mutation.ResetWalletBalanceCentavos()
	_u.mutation.SetWalletBalanceCentavos(v)
	return _u
}

// SetNillableWalletBalanceCentavos sets the "wallet_balance_centavos" field if the given value is not nil.
func (_u *DriverProfileUpdateOne) SetNillableWalletBalanceCentavos(v *int64) *DriverProfileUpdateOne {
	if v != nil {
		_u.SetWalletBalanceCentavos(*v)
	}
	return _u
}

// AddWalletBalanceCentavos adds value to the "wallet_balance_centavos" field.
func (_u *DriverProfileUpdateOne) AddWalletBalanceCentavos(v int64) *DriverProfileUpdateOne {
	_u.mutation.AddWalletBalanceCentavos(v)
	return _u
}

// Mutation returns the DriverProfileMutation object of the builder.
func (_u *DriverProfileUpdateOne) Mutation() *DriverProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the DriverProfileUpdate builder.
func (_u *DriverProfileUpdateOne) Where(ps ...predicate.DriverProfile) *DriverProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DriverProfileUpdateOne) Select(field string, fields ...string) *DriverProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DriverProfile entity.
func (_u *DriverProfileUpdateOne) Save(ctx context.Context) (*DriverProfile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DriverProfileUpdateOne) SaveX(ctx context.Context) *DriverProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DriverProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DriverProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DriverProfileUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := driverprofile.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "DriverProfile.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WalletBalanceCentavos(); ok {
		if err := driverprofile.WalletBalanceCentavosValidator(v); err != nil {
			return &ValidationError{Name: "wallet_balance_centavos", err: fmt.Errorf(`ent: validator failed for field "DriverProfile.wallet_balance_centavos": %w`, err)}
		}
	}
	return nil
}

func (_u *DriverProfileUpdateOne) sqlSave(ctx context.Context) (_node *DriverProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(driverprofile.Table, driverprofile.Columns, sqlgraph.NewFieldSpec(driverprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DriverProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, driverprofile.FieldID)
		for _, f := range fields {
			if !driverprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != driverprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(driverprofile.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(driverprofile.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(driverprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.VehicleType(); ok {
		_spec.SetField(driverprofile.FieldVehicleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlateNumber(); ok {
		_spec.SetField(driverprofile.FieldPlateNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(driverprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(driverprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsOnline(); ok {
		_spec.SetField(driverprofile.FieldIsOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WalletBalanceCentavos(); ok {
		_spec.SetField(driverprofile.FieldWalletBalanceCentavos, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWalletBalanceCentavos(); ok {
		_spec.AddField(driverprofile.FieldWalletBalanceCentavos, field.TypeInt64, value)
	}
	_node = &DriverProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{driverprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
