// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/driverdocument"
)

// DriverDocumentCreate is the builder for creating a DriverDocument entity.
type DriverDocumentCreate struct {
	config
	mutation *DriverDocumentMutation
	hooks    []Hook
}

// SetDriverID sets the "driver_id" field.
func (_c *DriverDocumentCreate) SetDriverID(v int) *DriverDocumentCreate {
	_c.mutation.SetDriverID(v)
	return _c
}

// SetDocumentType sets the "document_type" field.
func (_c *DriverDocumentCreate) SetDocumentType(v string) *DriverDocumentCreate {
	_c.mutation.SetDocumentType(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *DriverDocumentCreate) SetStorageKey(v string) *DriverDocumentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DriverDocumentCreate) SetStatus(v string) *DriverDocumentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableStatus(v *string) *DriverDocumentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *DriverDocumentCreate) SetContentType(v string) *DriverDocumentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableContentType(v *string) *DriverDocumentCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *DriverDocumentCreate) SetSizeBytes(v int64) *DriverDocumentCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableSizeBytes(v *int64) *DriverDocumentCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (_c *DriverDocumentCreate) SetChecksumSha256(v string) *DriverDocumentCreate {
	_c.mutation.SetChecksumSha256(v)
	return _c
}

// SetNillableChecksumSha256 sets the "checksum_sha256" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableChecksumSha256(v *string) *DriverDocumentCreate {
	if v != nil {
		_c.SetChecksumSha256(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DriverDocumentCreate) SetCreatedAt(v time.Time) *DriverDocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableCreatedAt(v *time.Time) *DriverDocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *DriverDocumentCreate) SetReviewedAt(v time.Time) *DriverDocumentCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableReviewedAt(v *time.Time) *DriverDocumentCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *DriverDocumentCreate) SetReviewedBy(v int) *DriverDocumentCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *DriverDocumentCreate) SetNillableReviewedBy(v *int) *DriverDocumentCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// Mutation returns the DriverDocumentMutation object of the builder.
func (_c *DriverDocumentCreate) Mutation() *DriverDocumentMutation {
	return _c.mutation
}

// Save creates the DriverDocument in the database.
func (_c *DriverDocumentCreate) Save(ctx context.Context) (*DriverDocument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DriverDocumentCreate) SaveX(ctx context.Context) *DriverDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriverDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriverDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DriverDocumentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := driverdocument.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		v := driverdocument.DefaultContentType
		_c.mutation.SetContentType(v)
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := driverdocument.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
	if _, ok := _c.mutation.ChecksumSha256(); !ok {
		v := driverdocument.DefaultChecksumSha256
		_c.mutation.SetChecksumSha256(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := driverdocument.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DriverDocumentCreate) check() error {
	if _, ok := _c.mutation.DriverID(); !ok {
		return &ValidationError{Name: "driver_id", err: errors.New(`ent: missing required field "DriverDocument.driver_id"`)}
	}
	if v, ok := _c.mutation.DriverID(); ok {
		if err := driverdocument.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.driver_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DocumentType(); !ok {
		return &ValidationError{Name: "document_type", err: errors.New(`ent: missing required field "DriverDocument.document_type"`)}
	}
	if v, ok := _c.mutation.DocumentType(); ok {
		if err := driverdocument.DocumentTypeValidator(v); err != nil {
			return &ValidationError{Name: "document_type", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.document_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "DriverDocument.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := driverdocument.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DriverDocument.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := driverdocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "DriverDocument.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := driverdocument.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "DriverDocument.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := driverdocument.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChecksumSha256(); !ok {
		return &ValidationError{Name: "checksum_sha256", err: errors.New(`ent: missing required field "DriverDocument.checksum_sha256"`)}
	}
	if v, ok := _c.mutation.ChecksumSha256(); ok {
		if err := driverdocument.ChecksumSha256Validator(v); err != nil {
			return &ValidationError{Name: "checksum_sha256", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.checksum_sha256": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReviewedBy(); ok {
		if err := driverdocument.ReviewedByValidator(v); err != nil {
			return &ValidationError{Name: "reviewed_by", err: fmt.Errorf(`ent: validator failed for field "DriverDocument.reviewed_by": %w`, err)}
		}
	}
	return nil
}

func (_c *DriverDocumentCreate) sqlSave(ctx context.Context) (*DriverDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DriverDocumentCreate) createSpec() (*DriverDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &DriverDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(driverdocument.Table, sqlgraph.NewFieldSpec(driverdocument.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DriverID(); ok {
		_spec.SetField(driverdocument.FieldDriverID, field.TypeInt, value)
		_node.DriverID = value
	}
	if value, ok := _c.mutation.DocumentType(); ok {
		_spec.SetField(driverdocument.FieldDocumentType, field.TypeString, value)
		_node.DocumentType = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(driverdocument.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(driverdocument.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(driverdocument.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(driverdocument.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.ChecksumSha256(); ok {
		_spec.SetField(driverdocument.FieldChecksumSha256, field.TypeString, value)
		_node.ChecksumSha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(driverdocument.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(driverdocument.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(driverdocument.FieldReviewedBy, field.TypeInt, value)
		_node.ReviewedBy = &value
	}
	return _node, _spec
}

// DriverDocumentCreateBulk is the builder for creating many DriverDocument entities in bulk.
type DriverDocumentCreateBulk struct {
	config
	err      error
	builders []*DriverDocumentCreate
}

// Save creates the DriverDocument entities in the database.
func (_c *DriverDocumentCreateBulk) Save(ctx context.Context) ([]*DriverDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DriverDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DriverDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DriverDocumentCreateBulk) SaveX(ctx context.Context) []*DriverDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriverDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriverDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
