// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/privateobject"
)

// PrivateObjectCreate is the builder for creating a PrivateObject entity.
type PrivateObjectCreate struct {
	config
	mutation *PrivateObjectMutation
	hooks    []Hook
}

// SetStorageKey sets the "storage_key" field.
func (_c *PrivateObjectCreate) SetStorageKey(v string) *PrivateObjectCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *PrivateObjectCreate) SetContent(v []byte) *PrivateObjectCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *PrivateObjectCreate) SetContentType(v string) *PrivateObjectCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *PrivateObjectCreate) SetSizeBytes(v int64) *PrivateObjectCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetChecksumSha256 sets the "checksum_sha256" field.
func (_c *PrivateObjectCreate) SetChecksumSha256(v string) *PrivateObjectCreate {
	_c.mutation.SetChecksumSha256(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PrivateObjectCreate) SetCreatedAt(v time.Time) *PrivateObjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PrivateObjectCreate) SetNillableCreatedAt(v *time.Time) *PrivateObjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the PrivateObjectMutation object of the builder.
func (_c *PrivateObjectCreate) Mutation() *PrivateObjectMutation {
	return _c.mutation
}

// Save creates the PrivateObject in the database.
func (_c *PrivateObjectCreate) Save(ctx context.Context) (*PrivateObject, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PrivateObjectCreate) SaveX(ctx context.Context) *PrivateObject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrivateObjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrivateObjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PrivateObjectCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := privateobject.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PrivateObjectCreate) check() error {
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "PrivateObject.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := privateobject.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "PrivateObject.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "PrivateObject.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := privateobject.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "PrivateObject.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "PrivateObject.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := privateobject.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "PrivateObject.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "PrivateObject.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := privateobject.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "PrivateObject.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChecksumSha256(); !ok {
		return &ValidationError{Name: "checksum_sha256", err: errors.New(`ent: missing required field "PrivateObject.checksum_sha256"`)}
	}
	if v, ok := _c.mutation.ChecksumSha256(); ok {
		if err := privateobject.ChecksumSha256Validator(v); err != nil {
			return &ValidationError{Name: "checksum_sha256", err: fmt.Errorf(`ent: validator failed for field "PrivateObject.checksum_sha256": %w`, err)}
		}
	}
	return nil
}

func (_c *PrivateObjectCreate) sqlSave(ctx context.Context) (*PrivateObject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PrivateObjectCreate) createSpec() (*PrivateObject, *sqlgraph.CreateSpec) {
	var (
		_node = &PrivateObject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(privateobject.Table, sqlgraph.NewFieldSpec(privateobject.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(privateobject.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(privateobject.FieldContent, field.TypeBytes, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(privateobject.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(privateobject.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.ChecksumSha256(); ok {
		_spec.SetField(privateobject.FieldChecksumSha256, field.TypeString, value)
		_node.ChecksumSha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(privateobject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PrivateObjectCreateBulk is the builder for creating many PrivateObject entities in bulk.
type PrivateObjectCreateBulk struct {
	config
	err      error
	builders []*PrivateObjectCreate
}

// Save creates the PrivateObject entities in the database.
func (_c *PrivateObjectCreateBulk) Save(ctx context.Context) ([]*PrivateObject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PrivateObject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrivateObjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PrivateObjectCreateBulk) SaveX(ctx context.Context) []*PrivateObject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrivateObjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrivateObjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
