// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/review"
)

// ReviewCreate is the builder for creating a Review entity.
type ReviewCreate struct {
	config
	mutation *ReviewMutation
	hooks    []Hook
}

// SetDriverID sets the "driver_id" field.
func (_c *ReviewCreate) SetDriverID(v int) *ReviewCreate {
	_c.mutation.SetDriverID(v)
	return _c
}

// SetPassengerID sets the "passenger_id" field.
func (_c *ReviewCreate) SetPassengerID(v int) *ReviewCreate {
	_c.mutation.SetPassengerID(v)
	return _c
}

// SetPassengerName sets the "passenger_name" field.
func (_c *ReviewCreate) SetPassengerName(v string) *ReviewCreate {
	_c.mutation.SetPassengerName(v)
	return _c
}

// SetNillablePassengerName sets the "passenger_name" field if the given value is not nil.
func (_c *ReviewCreate) SetNillablePassengerName(v *string) *ReviewCreate {
	if v != nil {
		_c.SetPassengerName(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *ReviewCreate) SetRating(v float64) *ReviewCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *ReviewCreate) SetComment(v string) *ReviewCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableComment(v *string) *ReviewCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReviewCreate) SetCreatedAt(v time.Time) *ReviewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReviewCreate) SetNillableCreatedAt(v *time.Time) *ReviewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReviewMutation object of the builder.
func (_c *ReviewCreate) Mutation() *ReviewMutation {
	return _c.mutation
}

// Save creates the Review in the database.
func (_c *ReviewCreate) Save(ctx context.Context) (*Review, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReviewCreate) SaveX(ctx context.Context) *Review {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReviewCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := review.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReviewCreate) check() error {
	if _, ok := _c.mutation.DriverID(); !ok {
		return &ValidationError{Name: "driver_id", err: errors.New(`ent: missing required field "Review.driver_id"`)}
	}
	if v, ok := _c.mutation.DriverID(); ok {
		if err := review.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "Review.driver_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PassengerID(); !ok {
		return &ValidationError{Name: "passenger_id", err: errors.New(`ent: missing required field "Review.passenger_id"`)}
	}
	if v, ok := _c.mutation.PassengerID(); ok {
		if err := review.PassengerIDValidator(v); err != nil {
			return &ValidationError{Name: "passenger_id", err: fmt.Errorf(`ent: validator failed for field "Review.passenger_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "Review.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := review.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Review.rating": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Review.created_at"`)}
	}
	return nil
}

func (_c *ReviewCreate) sqlSave(ctx context.Context) (*Review, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReviewCreate) createSpec() (*Review, *sqlgraph.CreateSpec) {
	var (
		_node = &Review{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(review.Table, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DriverID(); ok {
		_spec.SetField(review.FieldDriverID, field.TypeInt, value)
		_node.DriverID = value
	}
	if value, ok := _c.mutation.PassengerID(); ok {
		_spec.SetField(review.FieldPassengerID, field.TypeInt, value)
		_node.PassengerID = value
	}
	if value, ok := _c.mutation.PassengerName(); ok {
		_spec.SetField(review.FieldPassengerName, field.TypeString, value)
		_node.PassengerName = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(review.FieldRating, field.TypeFloat64, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(review.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(review.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ReviewCreateBulk is the builder for creating many Review entities in bulk.
type ReviewCreateBulk struct {
	config
	err      error
	builders []*ReviewCreate
}

// Save creates the Review entities in the database.
func (_c *ReviewCreateBulk) Save(ctx context.Context) ([]*Review, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Review, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReviewCreateBulk) SaveX(ctx context.Context) []*Review {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReviewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
