// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Easy-Bao/DrivingApp/server/ent/ridesettlement"
)

// RideSettlementCreate is the builder for creating a RideSettlement entity.
type RideSettlementCreate struct {
	config
	mutation *RideSettlementMutation
	hooks    []Hook
}

// SetRideID sets the "ride_id" field.
func (_c *RideSettlementCreate) SetRideID(v int) *RideSettlementCreate {
	_c.mutation.SetRideID(v)
	return _c
}

// SetGrossFareCentavos sets the "gross_fare_centavos" field.
func (_c *RideSettlementCreate) SetGrossFareCentavos(v int64) *RideSettlementCreate {
	_c.mutation.SetGrossFareCentavos(v)
	return _c
}

// SetCommissionBps sets the "commission_bps" field.
func (_c *RideSettlementCreate) SetCommissionBps(v int64) *RideSettlementCreate {
	_c.mutation.SetCommissionBps(v)
	return _c
}

// SetNillableCommissionBps sets the "commission_bps" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableCommissionBps(v *int64) *RideSettlementCreate {
	if v != nil {
		_c.SetCommissionBps(*v)
	}
	return _c
}

// SetCommissionCentavos sets the "commission_centavos" field.
func (_c *RideSettlementCreate) SetCommissionCentavos(v int64) *RideSettlementCreate {
	_c.mutation.SetCommissionCentavos(v)
	return _c
}

// SetNillableCommissionCentavos sets the "commission_centavos" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableCommissionCentavos(v *int64) *RideSettlementCreate {
	if v != nil {
		_c.SetCommissionCentavos(*v)
	}
	return _c
}

// SetDriverPayoutCentavos sets the "driver_payout_centavos" field.
func (_c *RideSettlementCreate) SetDriverPayoutCentavos(v int64) *RideSettlementCreate {
	_c.mutation.SetDriverPayoutCentavos(v)
	return _c
}

// SetNillableDriverPayoutCentavos sets the "driver_payout_centavos" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableDriverPayoutCentavos(v *int64) *RideSettlementCreate {
	if v != nil {
		_c.SetDriverPayoutCentavos(*v)
	}
	return _c
}

// SetPaymentStatus sets the "payment_status" field.
func (_c *RideSettlementCreate) SetPaymentStatus(v string) *RideSettlementCreate {
	_c.mutation.SetPaymentStatus(v)
	return _c
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillablePaymentStatus(v *string) *RideSettlementCreate {
	if v != nil {
		_c.SetPaymentStatus(*v)
	}
	return _c
}

// SetCashReceivedAt sets the "cash_received_at" field.
func (_c *RideSettlementCreate) SetCashReceivedAt(v time.Time) *RideSettlementCreate {
	_c.mutation.SetCashReceivedAt(v)
	return _c
}

// SetNillableCashReceivedAt sets the "cash_received_at" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableCashReceivedAt(v *time.Time) *RideSettlementCreate {
	if v != nil {
		_c.SetCashReceivedAt(*v)
	}
	return _c
}

// SetSettledAt sets the "settled_at" field.
func (_c *RideSettlementCreate) SetSettledAt(v time.Time) *RideSettlementCreate {
	_c.mutation.SetSettledAt(v)
	return _c
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableSettledAt(v *time.Time) *RideSettlementCreate {
	if v != nil {
		_c.SetSettledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RideSettlementCreate) SetCreatedAt(v time.Time) *RideSettlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableCreatedAt(v *time.Time) *RideSettlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RideSettlementCreate) SetUpdatedAt(v time.Time) *RideSettlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RideSettlementCreate) SetNillableUpdatedAt(v *time.Time) *RideSettlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RideSettlementMutation object of the builder.
func (_c *RideSettlementCreate) Mutation() *RideSettlementMutation {
	return _c.mutation
}

// Save creates the RideSettlement in the database.
func (_c *RideSettlementCreate) Save(ctx context.Context) (*RideSettlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RideSettlementCreate) SaveX(ctx context.Context) *RideSettlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RideSettlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RideSettlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RideSettlementCreate) defaults() {
	if _, ok := _c.mutation.CommissionCentavos(); !ok {
		v := ridesettlement.DefaultCommissionCentavos
		_c.mutation.SetCommissionCentavos(v)
	}
	if _, ok := _c.mutation.DriverPayoutCentavos(); !ok {
		v := ridesettlement.DefaultDriverPayoutCentavos
		_c.mutation.SetDriverPayoutCentavos(v)
	}
	if _, ok := _c.mutation.PaymentStatus(); !ok {
		v := ridesettlement.DefaultPaymentStatus
		_c.mutation.SetPaymentStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ridesettlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ridesettlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RideSettlementCreate) check() error {
	if _, ok := _c.mutation.RideID(); !ok {
		return &ValidationError{Name: "ride_id", err: errors.New(`ent: missing required field "RideSettlement.ride_id"`)}
	}
	if v, ok := _c.mutation.RideID(); ok {
		if err := ridesettlement.RideIDValidator(v); err != nil {
			return &ValidationError{Name: "ride_id", err: fmt.Errorf(`ent: validator failed for field "RideSettlement.ride_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GrossFareCentavos(); !ok {
		return &ValidationError{Name: "gross_fare_centavos", err: errors.New(`ent: missing required field "RideSettlement.gross_fare_centavos"`)}
	}
	if v, ok := _c.mutation.GrossFareCentavos(); ok {
		if err := ridesettlement.GrossFareCentavosValidator(v); err != nil {
			return &ValidationError{Name: "gross_fare_centavos", err: fmt.Errorf(`ent: validator failed for field "RideSettlement.gross_fare_centavos": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CommissionBps(); ok {
		if err := ridesettlement.CommissionBpsValidator(v); err != nil {
			return &ValidationError{Name: "commission_bps", err: fmt.Errorf(`ent: validator failed for field "RideSettlement.commission_bps": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommissionCentavos(); !ok {
		return &ValidationError{Name: "commission_centavos", err: errors.New(`ent: missing required field "RideSettlement.commission_centavos"`)}
	}
	if v, ok := _c.mutation.CommissionCentavos(); ok {
		if err := ridesettlement.CommissionCentavosValidator(v); err != nil {
			return &ValidationError{Name: "commission_centavos", err: fmt.Errorf(`ent: validator failed for field "RideSettlement.commission_centavos": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DriverPayoutCentavos(); !ok {
		return &ValidationError{Name: "driver_payout_centavos", err: errors.New(`ent: missing required field "RideSettlement.driver_payout_centavos"`)}
	}
	if v, ok := _c.mutation.DriverPayoutCentavos(); ok {
		if err := ridesettlement.DriverPayoutCentavosValidator(v); err != nil {
			return &ValidationError{Name: "driver_payout_centavos", err: fmt.Errorf(`ent: validator failed for field "RideSettlement.driver_payout_centavos": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentStatus(); !ok {
		return &ValidationError{Name: "payment_status", err: errors.New(`ent: missing required field "RideSettlement.payment_status"`)}
	}
	return nil
}

func (_c *RideSettlementCreate) sqlSave(ctx context.Context) (*RideSettlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RideSettlementCreate) createSpec() (*RideSettlement, *sqlgraph.CreateSpec) {
	var (
		_node = &RideSettlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ridesettlement.Table, sqlgraph.NewFieldSpec(ridesettlement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RideID(); ok {
		_spec.SetField(ridesettlement.FieldRideID, field.TypeInt, value)
		_node.RideID = value
	}
	if value, ok := _c.mutation.GrossFareCentavos(); ok {
		_spec.SetField(ridesettlement.FieldGrossFareCentavos, field.TypeInt64, value)
		_node.GrossFareCentavos = value
	}
	if value, ok := _c.mutation.CommissionBps(); ok {
		_spec.SetField(ridesettlement.FieldCommissionBps, field.TypeInt64, value)
		_node.CommissionBps = &value
	}
	if value, ok := _c.mutation.CommissionCentavos(); ok {
		_spec.SetField(ridesettlement.FieldCommissionCentavos, field.TypeInt64, value)
		_node.CommissionCentavos = value
	}
	if value, ok := _c.mutation.DriverPayoutCentavos(); ok {
		_spec.SetField(ridesettlement.FieldDriverPayoutCentavos, field.TypeInt64, value)
		_node.DriverPayoutCentavos = value
	}
	if value, ok := _c.mutation.PaymentStatus(); ok {
		_spec.SetField(ridesettlement.FieldPaymentStatus, field.TypeString, value)
		_node.PaymentStatus = value
	}
	if value, ok := _c.mutation.CashReceivedAt(); ok {
		_spec.SetField(ridesettlement.FieldCashReceivedAt, field.TypeTime, value)
		_node.CashReceivedAt = &value
	}
	if value, ok := _c.mutation.SettledAt(); ok {
		_spec.SetField(ridesettlement.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ridesettlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ridesettlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RideSettlementCreateBulk is the builder for creating many RideSettlement entities in bulk.
type RideSettlementCreateBulk struct {
	config
	err      error
	builders []*RideSettlementCreate
}

// Save creates the RideSettlement entities in the database.
func (_c *RideSettlementCreateBulk) Save(ctx context.Context) ([]*RideSettlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RideSettlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RideSettlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RideSettlementCreateBulk) SaveX(ctx context.Context) []*RideSettlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RideSettlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RideSettlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
