// Code generated by ent, DO NOT EDIT.

package passengerreview

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the passengerreview type in the database.
	Label = "passenger_review"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRideID holds the string denoting the ride_id field in the database.
	FieldRideID = "ride_id"
	// FieldDriverID holds the string denoting the driver_id field in the database.
	FieldDriverID = "driver_id"
	// FieldPassengerID holds the string denoting the passenger_id field in the database.
	FieldPassengerID = "passenger_id"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the passengerreview in the database.
	Table = "passenger_reviews"
)

// Columns holds all SQL columns for passengerreview fields.
var Columns = []string{
	FieldID,
	FieldRideID,
	FieldDriverID,
	FieldPassengerID,
	FieldRating,
	FieldComment,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RideIDValidator is a validator for the "ride_id" field. It is called by the builders before save.
	RideIDValidator func(int) error
	// DriverIDValidator is a validator for the "driver_id" field. It is called by the builders before save.
	DriverIDValidator func(int) error
	// PassengerIDValidator is a validator for the "passenger_id" field. It is called by the builders before save.
	PassengerIDValidator func(int) error
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PassengerReview queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRideID orders the results by the ride_id field.
func ByRideID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRideID, opts...).ToFunc()
}

// ByDriverID orders the results by the driver_id field.
func ByDriverID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriverID, opts...).ToFunc()
}

// ByPassengerID orders the results by the passenger_id field.
func ByPassengerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerID, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
