name: drive_app_workspace
repository: https://github.com/Easy-Bao/DrivingApp

packages:
  - apps/*
  - packages/*


scripts:
  postbootstrap:
    exec: flutter pub get
    description: Run pub get in all packages after bootstrapping.


  analyze:
    exec: flutter analyze .
    description: Run flutter analyzer on all packages.
