name: bao_ride
description: "A Booking App Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router_modular: ^5.0.5

  # State Management
  flutter_bloc: ^9.1.0

  # Data Models & Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI
  flutter_lucide: ^1.8.2

  # Dependency Injection
  get_it: ^8.0.3

  # Environment
  flutter_dotenv: ^6.0.1

  # Maps & Location
  mapbox_maps_flutter: ^2.23.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

  melos: ^6.2.0

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  # Code Generation
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product_Sans_Bold_Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Product_Sans_Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Product_Sans_Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Product_Sans_Regular.ttf
          weight: 400
          style: normal
