// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A nearby driver available for ride matching.
/// Returned to Flutter as a selectable list item.
class NearbyDriver {
  final String id;
  final String name;
  final String vehicleType;
  final String plateNumber;
  final double rating;
  final double lat;
  final double lng;
  final double distanceKm;
  final double etaMinutes;
  final double score;

  const NearbyDriver({
    required this.id,
    required this.name,
    required this.vehicleType,
    required this.plateNumber,
    required this.rating,
    required this.lat,
    required this.lng,
    required this.distanceKm,
    required this.etaMinutes,
    required this.score,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      vehicleType.hashCode ^
      plateNumber.hashCode ^
      rating.hashCode ^
      lat.hashCode ^
      lng.hashCode ^
      distanceKm.hashCode ^
      etaMinutes.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NearbyDriver &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          vehicleType == other.vehicleType &&
          plateNumber == other.plateNumber &&
          rating == other.rating &&
          lat == other.lat &&
          lng == other.lng &&
          distanceKm == other.distanceKm &&
          etaMinutes == other.etaMinutes &&
          score == other.score;
}
