// Code generated by ent, DO NOT EDIT.

package privateobject

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Easy-Bao/DrivingApp/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldID, id))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldStorageKey, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldContent, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldContentType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldSizeBytes, v))
}

// ChecksumSha256 applies equality check predicate on the "checksum_sha256" field. It's identical to ChecksumSha256EQ.
func ChecksumSha256(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldChecksumSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldCreatedAt, v))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldContainsFold(FieldStorageKey, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...[]byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...[]byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v []byte) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldContent, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldContainsFold(FieldContentType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldSizeBytes, v))
}

// ChecksumSha256EQ applies the EQ predicate on the "checksum_sha256" field.
func ChecksumSha256EQ(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldChecksumSha256, v))
}

// ChecksumSha256NEQ applies the NEQ predicate on the "checksum_sha256" field.
func ChecksumSha256NEQ(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldChecksumSha256, v))
}

// ChecksumSha256In applies the In predicate on the "checksum_sha256" field.
func ChecksumSha256In(vs ...string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldChecksumSha256, vs...))
}

// ChecksumSha256NotIn applies the NotIn predicate on the "checksum_sha256" field.
func ChecksumSha256NotIn(vs ...string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldChecksumSha256, vs...))
}

// ChecksumSha256GT applies the GT predicate on the "checksum_sha256" field.
func ChecksumSha256GT(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldChecksumSha256, v))
}

// ChecksumSha256GTE applies the GTE predicate on the "checksum_sha256" field.
func ChecksumSha256GTE(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldChecksumSha256, v))
}

// ChecksumSha256LT applies the LT predicate on the "checksum_sha256" field.
func ChecksumSha256LT(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldChecksumSha256, v))
}

// ChecksumSha256LTE applies the LTE predicate on the "checksum_sha256" field.
func ChecksumSha256LTE(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldChecksumSha256, v))
}

// ChecksumSha256Contains applies the Contains predicate on the "checksum_sha256" field.
func ChecksumSha256Contains(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldContains(FieldChecksumSha256, v))
}

// ChecksumSha256HasPrefix applies the HasPrefix predicate on the "checksum_sha256" field.
func ChecksumSha256HasPrefix(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldHasPrefix(FieldChecksumSha256, v))
}

// ChecksumSha256HasSuffix applies the HasSuffix predicate on the "checksum_sha256" field.
func ChecksumSha256HasSuffix(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldHasSuffix(FieldChecksumSha256, v))
}

// ChecksumSha256EqualFold applies the EqualFold predicate on the "checksum_sha256" field.
func ChecksumSha256EqualFold(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEqualFold(FieldChecksumSha256, v))
}

// ChecksumSha256ContainsFold applies the ContainsFold predicate on the "checksum_sha256" field.
func ChecksumSha256ContainsFold(v string) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldContainsFold(FieldChecksumSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PrivateObject {
	return predicate.PrivateObject(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrivateObject) predicate.PrivateObject {
	return predicate.PrivateObject(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrivateObject) predicate.PrivateObject {
	return predicate.PrivateObject(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrivateObject) predicate.PrivateObject {
	return predicate.PrivateObject(sql.NotPredicates(p))
}
