package domain

import "errors"

var (
	ErrInvalidTrip             = errors.New("invalid trip details")
	ErrInvalidDriverStanding   = errors.New("invalid driver standing")
	ErrRouteUnavailable        = errors.New("route calculation is unavailable")
	ErrActiveBooking           = errors.New("passenger already has an active booking")
	ErrDriverHasActiveRide     = errors.New("driver already has an active ride")
	ErrDriverSettlementOverdue = errors.New("driver has an overdue cash settlement")
	ErrUnauthorizedRide        = errors.New("you are not a participant in this ride")
	ErrCounterpartyUnavailable = errors.New("ride counterparty is unavailable")
	ErrUnauthorizedSession     = errors.New("you are not a participant in this booking")
	ErrInvalidFareOffer        = errors.New("offer must not be lower than the calculated minimum fare")
	ErrInvalidSettlement       = errors.New("invalid settlement terms")
	ErrDriverUnavailable       = errors.New("driver is unavailable")
	ErrDuplicateBid            = errors.New("driver already submitted a bid for this ride")
	ErrInvalidStatusTransition = errors.New("invalid ride status transition")
	ErrInvalidCancellation     = errors.New("invalid ride cancellation")
	ErrCancellationCommand     = errors.New("ride cancellation requires a cancellation command")
	ErrArrivalCommand          = errors.New("ride arrival requires the arrival command")
	ErrTripStartCommand        = errors.New("trip start requires the start command")
	ErrTripCompletionCommand   = errors.New("trip completion requires the completion command")
	ErrArrivalLocation         = errors.New("driver is not close enough to the pickup")
	ErrCompletionLocation      = errors.New("driver is not close enough to the destination")
	ErrPassengerNoShowNotReady = errors.New("the passenger wait period has not elapsed")
	ErrNoShowCommand           = errors.New("passenger no-show requires the no-show command")
	ErrReviewNotAllowed        = errors.New("reviews are allowed only after a completed ride")
	ErrReviewAlreadySubmitted  = errors.New("a review was already submitted for this ride")
	ErrSafetyReportNotAllowed  = errors.New("you cannot report this ride")
	ErrSafetyReportInvalid     = errors.New("the safety report is invalid")
	ErrSafetyReportAlreadySent = errors.New("this report was already submitted")
)
