// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_valid_sequence`, `permute`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Compute the fare for a ride given distance, duration, and pricing config.
///
/// All monetary values are in PHP (₱).
/// The computation applies:
/// 1. Base fare
/// 2. Distance charge = distance_km × per_km_rate
/// 3. Time charge = duration_minutes × per_minute_rate
/// 4. Subtotal = base + distance + time
/// 5. Surge = subtotal × (surge_multiplier - 1.0)
/// 6. Total = subtotal + surge, clamped to minimum_fare
/// 7. Rounded to nearest ₱0.50
Future<FareResult> computeFare({
  required double distanceKm,
  required double durationMinutes,
  required FareConfig config,
}) => RustLib.instance.api.crateApplicationFareEngineComputeFare(
  distanceKm: distanceKm,
  durationMinutes: durationMinutes,
  config: config,
);

/// Compute fare with default BaoBao pricing.
///
/// Default rates:
/// - Base fare: ₱20.00
/// - Per km: ₱10.00
/// - Per minute: ₱1.50
/// - Surge: 1.0× (no surge)
/// - Minimum: ₱25.00
Future<FareResult> computeFareDefault({
  required double distanceKm,
  required double durationMinutes,
}) => RustLib.instance.api.crateApplicationFareEngineComputeFareDefault(
  distanceKm: distanceKm,
  durationMinutes: durationMinutes,
);

/// Calculate surge heatmap grid using Kernel Density Estimation (KDE)
Future<List<HeatmapCell>> calculateSurgeHeatmap({
  required double centerLat,
  required double centerLng,
  required int gridSize,
  required double cellSizeDegrees,
  required List<double> requestLats,
  required List<double> requestLngs,
}) => RustLib.instance.api.crateApplicationFareEngineCalculateSurgeHeatmap(
  centerLat: centerLat,
  centerLng: centerLng,
  gridSize: gridSize,
  cellSizeDegrees: cellSizeDegrees,
  requestLats: requestLats,
  requestLngs: requestLngs,
);

/// Calculate the optimal route sequence using a TSP search with pickup-before-dropoff constraints.
Future<RouteSequenceResult> calculateOptimalRoute({
  required double startLat,
  required double startLng,
  required List<Waypoint> waypoints,
}) => RustLib.instance.api.crateApplicationFareEngineCalculateOptimalRoute(
  startLat: startLat,
  startLng: startLng,
  waypoints: waypoints,
);

/// Configuration for fare calculation.
class FareConfig {
  final double baseFare;
  final double perKmRate;
  final double perMinuteRate;
  final double surgeMultiplier;
  final double minimumFare;

  const FareConfig({
    required this.baseFare,
    required this.perKmRate,
    required this.perMinuteRate,
    required this.surgeMultiplier,
    required this.minimumFare,
  });

  @override
  int get hashCode =>
      baseFare.hashCode ^
      perKmRate.hashCode ^
      perMinuteRate.hashCode ^
      surgeMultiplier.hashCode ^
      minimumFare.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FareConfig &&
          runtimeType == other.runtimeType &&
          baseFare == other.baseFare &&
          perKmRate == other.perKmRate &&
          perMinuteRate == other.perMinuteRate &&
          surgeMultiplier == other.surgeMultiplier &&
          minimumFare == other.minimumFare;
}

/// Result of a fare calculation.
class FareResult {
  final double baseFare;
  final double distanceCharge;
  final double timeCharge;
  final double surgeCharge;
  final double totalFare;

  const FareResult({
    required this.baseFare,
    required this.distanceCharge,
    required this.timeCharge,
    required this.surgeCharge,
    required this.totalFare,
  });

  @override
  int get hashCode =>
      baseFare.hashCode ^
      distanceCharge.hashCode ^
      timeCharge.hashCode ^
      surgeCharge.hashCode ^
      totalFare.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FareResult &&
          runtimeType == other.runtimeType &&
          baseFare == other.baseFare &&
          distanceCharge == other.distanceCharge &&
          timeCharge == other.timeCharge &&
          surgeCharge == other.surgeCharge &&
          totalFare == other.totalFare;
}

class HeatmapCell {
  final double lat;
  final double lng;
  final double intensity;

  const HeatmapCell({
    required this.lat,
    required this.lng,
    required this.intensity,
  });

  @override
  int get hashCode => lat.hashCode ^ lng.hashCode ^ intensity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeatmapCell &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lng == other.lng &&
          intensity == other.intensity;
}

class RouteSequenceResult {
  final List<Waypoint> optimalSequence;
  final double totalDistanceKm;

  const RouteSequenceResult({
    required this.optimalSequence,
    required this.totalDistanceKm,
  });

  @override
  int get hashCode => optimalSequence.hashCode ^ totalDistanceKm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteSequenceResult &&
          runtimeType == other.runtimeType &&
          optimalSequence == other.optimalSequence &&
          totalDistanceKm == other.totalDistanceKm;
}

class Waypoint {
  final String id;
  final String name;
  final double lat;
  final double lng;
  final bool isPickup;
  final String passengerId;

  const Waypoint({
    required this.id,
    required this.name,
    required this.lat,
    required this.lng,
    required this.isPickup,
    required this.passengerId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      lat.hashCode ^
      lng.hashCode ^
      isPickup.hashCode ^
      passengerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Waypoint &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lat == other.lat &&
          lng == other.lng &&
          isPickup == other.isPickup &&
          passengerId == other.passengerId;
}
