// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/models.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Calculate the great-circle distance between two points in kilometers.
Future<double> haversineDistance({
  required double lat1,
  required double lng1,
  required double lat2,
  required double lng2,
}) => RustLib.instance.api.crateApplicationMapApiHaversineDistance(
  lat1: lat1,
  lng1: lng1,
  lat2: lat2,
  lng2: lng2,
);

/// Search for places using Mapbox Geocoding API.
Future<List<RustPlaceResult>> searchPlaces({
  required String token,
  required String query,
  double? proximityLat,
  double? proximityLng,
  double? userLat,
  double? userLng,
}) => RustLib.instance.api.crateApplicationMapApiSearchPlaces(
  token: token,
  query: query,
  proximityLat: proximityLat,
  proximityLng: proximityLng,
  userLat: userLat,
  userLng: userLng,
);

/// Get place info from coordinates using Mapbox Geocoding API.
Future<RustPlaceResult?> reverseGeocode({
  required String token,
  required double lat,
  required double lng,
}) => RustLib.instance.api.crateApplicationMapApiReverseGeocode(
  token: token,
  lat: lat,
  lng: lng,
);

/// Get a driving route between two points.
Future<RustRouteResult?> getRoute({
  required String token,
  required double originLat,
  required double originLng,
  required double destLat,
  required double destLng,
}) => RustLib.instance.api.crateApplicationMapApiGetRoute(
  token: token,
  originLat: originLat,
  originLng: originLng,
  destLat: destLat,
  destLng: destLng,
);

/// Extract all dynamic Points of Interest from Mapbox vector tiles within a radius
Future<List<RustPlaceResult>> getNearbyPois({
  required String token,
  required double lat,
  required double lng,
}) => RustLib.instance.api.crateApplicationMapApiGetNearbyPois(
  token: token,
  lat: lat,
  lng: lng,
);
