targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/features/map/domain/failures/{{}}.dart': 'lib/src/features/map/domain/failures/generated/{{}}.g.dart'
      freezed|freezed:
        options:
          build_extensions:
            '^lib/src/features/map/domain/failures/{{}}.dart': 'lib/src/features/map/domain/failures/generated/{{}}.freezed.dart'
