// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bidding.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBidSession = `-- name: CancelBidSession :one
UPDATE bid_sessions
SET status = 'cancelled'
WHERE id = $1
  AND passenger_id = $2
  AND status = 'open'
RETURNING id, passenger_id, ride_type, pickup_latitude, pickup_longitude,
    pickup_name, dropoff_latitude, dropoff_longitude, dropoff_name,
    passenger_note, distance_km, duration_minutes, offered_fare_centavos,
    status, target_driver_id, accepted_driver_id, expires_at, created_at
`

type CancelBidSessionParams struct {
	ID          int32 `db:"id"`
	PassengerID int32 `db:"passenger_id"`
}

func (q *Queries) CancelBidSession(ctx context.Context, arg CancelBidSessionParams) (BidSession, error) {
	row := q.db.QueryRow(ctx, cancelBidSession, arg.ID, arg.PassengerID)
	var i BidSession
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.PassengerNote,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.OfferedFareCentavos,
		&i.Status,
		&i.TargetDriverID,
		&i.AcceptedDriverID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveRidesForDriver = `-- name: CountActiveRidesForDriver :one
SELECT count(*)
FROM rides
WHERE driver_id = $1
  AND status IN ('assigned', 'accepted', 'arrived', 'in_transit')
`

func (q *Queries) CountActiveRidesForDriver(ctx context.Context, driverID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRidesForDriver, driverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBidOffer = `-- name: CreateBidOffer :one
INSERT INTO bid_offers (
    session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status, created_at
`

type CreateBidOfferParams struct {
	SessionID            int32       `db:"session_id"`
	DriverID             int32       `db:"driver_id"`
	DriverName           pgtype.Text `db:"driver_name"`
	PlateNumber          pgtype.Text `db:"plate_number"`
	VehicleType          pgtype.Text `db:"vehicle_type"`
	ProposedFareCentavos int64       `db:"proposed_fare_centavos"`
}

func (q *Queries) CreateBidOffer(ctx context.Context, arg CreateBidOfferParams) (BidOffer, error) {
	row := q.db.QueryRow(ctx, createBidOffer,
		arg.SessionID,
		arg.DriverID,
		arg.DriverName,
		arg.PlateNumber,
		arg.VehicleType,
		arg.ProposedFareCentavos,
	)
	var i BidOffer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DriverID,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleType,
		&i.ProposedFareCentavos,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createBidSession = `-- name: CreateBidSession :one
INSERT INTO bid_sessions (
    passenger_id, ride_type, pickup_latitude, pickup_longitude, pickup_name,
    dropoff_latitude, dropoff_longitude, dropoff_name, passenger_note,
    distance_km, duration_minutes, offered_fare_centavos, status,
    target_driver_id, expires_at, created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    COALESCE($16::timestamptz, CURRENT_TIMESTAMP)
)
RETURNING id, passenger_id, ride_type, pickup_latitude, pickup_longitude,
    pickup_name, dropoff_latitude, dropoff_longitude, dropoff_name,
    passenger_note, distance_km, duration_minutes, offered_fare_centavos,
    status, target_driver_id, accepted_driver_id, expires_at, created_at
`

type CreateBidSessionParams struct {
	PassengerID         int32              `db:"passenger_id"`
	RideType            string             `db:"ride_type"`
	PickupLatitude      float64            `db:"pickup_latitude"`
	PickupLongitude     float64            `db:"pickup_longitude"`
	PickupName          string             `db:"pickup_name"`
	DropoffLatitude     float64            `db:"dropoff_latitude"`
	DropoffLongitude    float64            `db:"dropoff_longitude"`
	DropoffName         string             `db:"dropoff_name"`
	PassengerNote       pgtype.Text        `db:"passenger_note"`
	DistanceKm          float64            `db:"distance_km"`
	DurationMinutes     float64            `db:"duration_minutes"`
	OfferedFareCentavos int64              `db:"offered_fare_centavos"`
	Status              string             `db:"status"`
	TargetDriverID      pgtype.Int4        `db:"target_driver_id"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateBidSession(ctx context.Context, arg CreateBidSessionParams) (BidSession, error) {
	row := q.db.QueryRow(ctx, createBidSession,
		arg.PassengerID,
		arg.RideType,
		arg.PickupLatitude,
		arg.PickupLongitude,
		arg.PickupName,
		arg.DropoffLatitude,
		arg.DropoffLongitude,
		arg.DropoffName,
		arg.PassengerNote,
		arg.DistanceKm,
		arg.DurationMinutes,
		arg.OfferedFareCentavos,
		arg.Status,
		arg.TargetDriverID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i BidSession
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.PassengerNote,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.OfferedFareCentavos,
		&i.Status,
		&i.TargetDriverID,
		&i.AcceptedDriverID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireBidSessions = `-- name: ExpireBidSessions :exec
UPDATE bid_sessions
SET status = 'expired'
WHERE passenger_id = $1
  AND status = 'open'
  AND expires_at <= $2
`

type ExpireBidSessionsParams struct {
	PassengerID int32              `db:"passenger_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) ExpireBidSessions(ctx context.Context, arg ExpireBidSessionsParams) error {
	_, err := q.db.Exec(ctx, expireBidSessions, arg.PassengerID, arg.ExpiresAt)
	return err
}

const getBidSessionByID = `-- name: GetBidSessionByID :one
SELECT id, passenger_id, ride_type, pickup_latitude, pickup_longitude,
    pickup_name, dropoff_latitude, dropoff_longitude, dropoff_name,
    passenger_note, distance_km, duration_minutes, offered_fare_centavos,
    status, target_driver_id, accepted_driver_id, expires_at, created_at
FROM bid_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBidSessionByID(ctx context.Context, id int32) (BidSession, error) {
	row := q.db.QueryRow(ctx, getBidSessionByID, id)
	var i BidSession
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.PassengerNote,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.OfferedFareCentavos,
		&i.Status,
		&i.TargetDriverID,
		&i.AcceptedDriverID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOnlineDriverProfileForBidding = `-- name: GetOnlineDriverProfileForBidding :one
SELECT id, user_id, name, vehicle_type, plate_number, rating, is_online,
    wallet_balance_centavos
FROM driver_profiles
WHERE user_id = $1
  AND is_online = true
LIMIT 1
`

func (q *Queries) GetOnlineDriverProfileForBidding(ctx context.Context, userID int32) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getOnlineDriverProfileForBidding, userID)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.VehicleType,
		&i.PlateNumber,
		&i.Rating,
		&i.IsOnline,
		&i.WalletBalanceCentavos,
	)
	return i, err
}

const getPendingBidOffer = `-- name: GetPendingBidOffer :one
SELECT id, session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status, created_at
FROM bid_offers
WHERE session_id = $1
  AND driver_id = $2
  AND status = 'pending'
LIMIT 1
`

type GetPendingBidOfferParams struct {
	SessionID int32 `db:"session_id"`
	DriverID  int32 `db:"driver_id"`
}

func (q *Queries) GetPendingBidOffer(ctx context.Context, arg GetPendingBidOfferParams) (BidOffer, error) {
	row := q.db.QueryRow(ctx, getPendingBidOffer, arg.SessionID, arg.DriverID)
	var i BidOffer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DriverID,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleType,
		&i.ProposedFareCentavos,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveBidSession = `-- name: HasActiveBidSession :one
SELECT EXISTS (
    SELECT 1
    FROM bid_sessions
    WHERE passenger_id = $1
      AND status = 'open'
      AND expires_at > $2
)
`

type HasActiveBidSessionParams struct {
	PassengerID int32              `db:"passenger_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) HasActiveBidSession(ctx context.Context, arg HasActiveBidSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveBidSession, arg.PassengerID, arg.ExpiresAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActivePassengerRide = `-- name: HasActivePassengerRide :one
SELECT EXISTS (
    SELECT 1
    FROM rides
    WHERE passenger_id = $1
      AND status IN ('requested', 'assigned', 'accepted', 'arrived', 'in_transit')
)
`

func (q *Queries) HasActivePassengerRide(ctx context.Context, passengerID int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasActivePassengerRide, passengerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasPendingBidOffer = `-- name: HasPendingBidOffer :one
SELECT EXISTS (
    SELECT 1
    FROM bid_offers
    WHERE session_id = $1
      AND driver_id = $2
      AND status = 'pending'
)
`

type HasPendingBidOfferParams struct {
	SessionID int32 `db:"session_id"`
	DriverID  int32 `db:"driver_id"`
}

func (q *Queries) HasPendingBidOffer(ctx context.Context, arg HasPendingBidOfferParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingBidOffer, arg.SessionID, arg.DriverID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveBidSessions = `-- name: ListActiveBidSessions :many
SELECT sessions.id, sessions.passenger_id, sessions.ride_type,
    sessions.pickup_latitude, sessions.pickup_longitude, sessions.pickup_name,
    sessions.dropoff_latitude, sessions.dropoff_longitude, sessions.dropoff_name,
    sessions.passenger_note, sessions.distance_km, sessions.duration_minutes,
    sessions.offered_fare_centavos, sessions.status, sessions.target_driver_id,
    sessions.accepted_driver_id, sessions.expires_at, sessions.created_at
FROM bid_sessions AS sessions
WHERE sessions.status = 'open'
  AND sessions.expires_at > $1
ORDER BY sessions.created_at
LIMIT 50
`

func (q *Queries) ListActiveBidSessions(ctx context.Context, expiresAt pgtype.Timestamptz) ([]BidSession, error) {
	rows, err := q.db.Query(ctx, listActiveBidSessions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidSession{}
	for rows.Next() {
		var i BidSession
		if err := rows.Scan(
			&i.ID,
			&i.PassengerID,
			&i.RideType,
			&i.PickupLatitude,
			&i.PickupLongitude,
			&i.PickupName,
			&i.DropoffLatitude,
			&i.DropoffLongitude,
			&i.DropoffName,
			&i.PassengerNote,
			&i.DistanceKm,
			&i.DurationMinutes,
			&i.OfferedFareCentavos,
			&i.Status,
			&i.TargetDriverID,
			&i.AcceptedDriverID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBidOffersBySession = `-- name: ListBidOffersBySession :many
SELECT id, session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status, created_at
FROM bid_offers
WHERE session_id = $1
ORDER BY created_at
`

func (q *Queries) ListBidOffersBySession(ctx context.Context, sessionID int32) ([]BidOffer, error) {
	rows, err := q.db.Query(ctx, listBidOffersBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidOffer{}
	for rows.Next() {
		var i BidOffer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DriverID,
			&i.DriverName,
			&i.PlateNumber,
			&i.VehicleType,
			&i.ProposedFareCentavos,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetedActiveBidSessions = `-- name: ListTargetedActiveBidSessions :many
SELECT sessions.id, sessions.passenger_id, sessions.ride_type,
    sessions.pickup_latitude, sessions.pickup_longitude, sessions.pickup_name,
    sessions.dropoff_latitude, sessions.dropoff_longitude, sessions.dropoff_name,
    sessions.passenger_note, sessions.distance_km, sessions.duration_minutes,
    sessions.offered_fare_centavos, sessions.status, sessions.target_driver_id,
    sessions.accepted_driver_id, sessions.expires_at, sessions.created_at
FROM bid_sessions AS sessions
WHERE sessions.status = 'open'
  AND sessions.expires_at > $1
  AND (sessions.target_driver_id IS NULL OR sessions.target_driver_id = $2)
  AND NOT EXISTS (
      SELECT 1
      FROM bid_offers AS offers
      WHERE offers.session_id = sessions.id
        AND offers.driver_id = $2
        AND offers.status = 'pending'
  )
ORDER BY sessions.created_at
LIMIT 50
`

type ListTargetedActiveBidSessionsParams struct {
	ExpiresAt      pgtype.Timestamptz `db:"expires_at"`
	TargetDriverID pgtype.Int4        `db:"target_driver_id"`
}

func (q *Queries) ListTargetedActiveBidSessions(ctx context.Context, arg ListTargetedActiveBidSessionsParams) ([]BidSession, error) {
	rows, err := q.db.Query(ctx, listTargetedActiveBidSessions, arg.ExpiresAt, arg.TargetDriverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BidSession{}
	for rows.Next() {
		var i BidSession
		if err := rows.Scan(
			&i.ID,
			&i.PassengerID,
			&i.RideType,
			&i.PickupLatitude,
			&i.PickupLongitude,
			&i.PickupName,
			&i.DropoffLatitude,
			&i.DropoffLongitude,
			&i.DropoffName,
			&i.PassengerNote,
			&i.DistanceKm,
			&i.DurationMinutes,
			&i.OfferedFareCentavos,
			&i.Status,
			&i.TargetDriverID,
			&i.AcceptedDriverID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOnlineDriverProfileForBidding = `-- name: LockOnlineDriverProfileForBidding :one
SELECT id, user_id, name, vehicle_type, plate_number, rating, is_online,
    wallet_balance_centavos
FROM driver_profiles
WHERE user_id = $1
  AND is_online = true
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockOnlineDriverProfileForBidding(ctx context.Context, userID int32) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, lockOnlineDriverProfileForBidding, userID)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.VehicleType,
		&i.PlateNumber,
		&i.Rating,
		&i.IsOnline,
		&i.WalletBalanceCentavos,
	)
	return i, err
}

const lockUserForBidSession = `-- name: LockUserForBidSession :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserForBidSession(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockUserForBidSession, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const rejectBidOffer = `-- name: RejectBidOffer :one
UPDATE bid_offers
SET status = 'rejected'
WHERE id = $1
  AND status = 'pending'
RETURNING id, session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status, created_at
`

func (q *Queries) RejectBidOffer(ctx context.Context, id int32) (BidOffer, error) {
	row := q.db.QueryRow(ctx, rejectBidOffer, id)
	var i BidOffer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DriverID,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleType,
		&i.ProposedFareCentavos,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
