// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ride_acceptance.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptRideFromRequest = `-- name: AcceptRideFromRequest :one
UPDATE rides
SET status = 'accepted',
    driver_id = $2,
    driver_name = $3,
    vehicle_type = $4,
    plate_number = $5,
    commission_bps = $6,
    commission_centavos = $7,
    driver_payout_centavos = $8
WHERE id = $1
  AND status = 'requested'
RETURNING id, passenger_id, driver_id, status, fare_centavos, ride_type,
    pickup_latitude, pickup_longitude, pickup_name,
    dropoff_latitude, dropoff_longitude, dropoff_name,
    distance_km, duration_minutes, driver_name, vehicle_type, plate_number,
    driver_rating, created_at, completed_at, payment_status,
    cash_received_at, commission_bps, commission_centavos,
    driver_payout_centavos
`

type AcceptRideFromRequestParams struct {
	ID                   int32       `db:"id"`
	DriverID             pgtype.Int4 `db:"driver_id"`
	DriverName           pgtype.Text `db:"driver_name"`
	VehicleType          pgtype.Text `db:"vehicle_type"`
	PlateNumber          pgtype.Text `db:"plate_number"`
	CommissionBps        pgtype.Int8 `db:"commission_bps"`
	CommissionCentavos   int64       `db:"commission_centavos"`
	DriverPayoutCentavos int64       `db:"driver_payout_centavos"`
}

func (q *Queries) AcceptRideFromRequest(ctx context.Context, arg AcceptRideFromRequestParams) (Ride, error) {
	row := q.db.QueryRow(ctx, acceptRideFromRequest,
		arg.ID,
		arg.DriverID,
		arg.DriverName,
		arg.VehicleType,
		arg.PlateNumber,
		arg.CommissionBps,
		arg.CommissionCentavos,
		arg.DriverPayoutCentavos,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.Status,
		&i.FareCentavos,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.DriverName,
		&i.VehicleType,
		&i.PlateNumber,
		&i.DriverRating,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PaymentStatus,
		&i.CashReceivedAt,
		&i.CommissionBps,
		&i.CommissionCentavos,
		&i.DriverPayoutCentavos,
	)
	return i, err
}

const assignRideFromAcceptance = `-- name: AssignRideFromAcceptance :one
UPDATE rides
SET status = 'assigned',
    driver_id = $2,
    driver_name = $3,
    vehicle_type = $4,
    plate_number = $5,
    commission_bps = $6,
    commission_centavos = $7,
    driver_payout_centavos = $8
WHERE id = $1
  AND status = 'requested'
RETURNING id, passenger_id, driver_id, status, fare_centavos, ride_type,
    pickup_latitude, pickup_longitude, pickup_name,
    dropoff_latitude, dropoff_longitude, dropoff_name,
    distance_km, duration_minutes, driver_name, vehicle_type, plate_number,
    driver_rating, created_at, completed_at, payment_status,
    cash_received_at, commission_bps, commission_centavos,
    driver_payout_centavos
`

type AssignRideFromAcceptanceParams struct {
	ID                   int32       `db:"id"`
	DriverID             pgtype.Int4 `db:"driver_id"`
	DriverName           pgtype.Text `db:"driver_name"`
	VehicleType          pgtype.Text `db:"vehicle_type"`
	PlateNumber          pgtype.Text `db:"plate_number"`
	CommissionBps        pgtype.Int8 `db:"commission_bps"`
	CommissionCentavos   int64       `db:"commission_centavos"`
	DriverPayoutCentavos int64       `db:"driver_payout_centavos"`
}

func (q *Queries) AssignRideFromAcceptance(ctx context.Context, arg AssignRideFromAcceptanceParams) (Ride, error) {
	row := q.db.QueryRow(ctx, assignRideFromAcceptance,
		arg.ID,
		arg.DriverID,
		arg.DriverName,
		arg.VehicleType,
		arg.PlateNumber,
		arg.CommissionBps,
		arg.CommissionCentavos,
		arg.DriverPayoutCentavos,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.Status,
		&i.FareCentavos,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.DriverName,
		&i.VehicleType,
		&i.PlateNumber,
		&i.DriverRating,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PaymentStatus,
		&i.CashReceivedAt,
		&i.CommissionBps,
		&i.CommissionCentavos,
		&i.DriverPayoutCentavos,
	)
	return i, err
}

const countActiveRidesForAcceptance = `-- name: CountActiveRidesForAcceptance :one
SELECT count(*)
FROM rides
WHERE driver_id = $1
  AND status IN ('requested', 'assigned', 'accepted', 'arrived', 'in_transit')
`

func (q *Queries) CountActiveRidesForAcceptance(ctx context.Context, driverID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRidesForAcceptance, driverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAcceptedRide = `-- name: CreateAcceptedRide :one
INSERT INTO rides (
    passenger_id, driver_id, status, fare_centavos, ride_type,
    pickup_latitude, pickup_longitude, pickup_name,
    dropoff_latitude, dropoff_longitude, dropoff_name,
    distance_km, duration_minutes, driver_name, vehicle_type, plate_number,
    commission_bps, commission_centavos, driver_payout_centavos
)
VALUES (
    $1, $2, 'accepted', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
RETURNING id, passenger_id, driver_id, status, fare_centavos, ride_type,
    pickup_latitude, pickup_longitude, pickup_name,
    dropoff_latitude, dropoff_longitude, dropoff_name,
    distance_km, duration_minutes, driver_name, vehicle_type, plate_number,
    driver_rating, created_at, completed_at, payment_status,
    cash_received_at, commission_bps, commission_centavos,
    driver_payout_centavos
`

type CreateAcceptedRideParams struct {
	PassengerID          int32         `db:"passenger_id"`
	DriverID             pgtype.Int4   `db:"driver_id"`
	FareCentavos         int64         `db:"fare_centavos"`
	RideType             string        `db:"ride_type"`
	PickupLatitude       pgtype.Float8 `db:"pickup_latitude"`
	PickupLongitude      pgtype.Float8 `db:"pickup_longitude"`
	PickupName           pgtype.Text   `db:"pickup_name"`
	DropoffLatitude      pgtype.Float8 `db:"dropoff_latitude"`
	DropoffLongitude     pgtype.Float8 `db:"dropoff_longitude"`
	DropoffName          pgtype.Text   `db:"dropoff_name"`
	DistanceKm           pgtype.Float8 `db:"distance_km"`
	DurationMinutes      pgtype.Float8 `db:"duration_minutes"`
	DriverName           pgtype.Text   `db:"driver_name"`
	VehicleType          pgtype.Text   `db:"vehicle_type"`
	PlateNumber          pgtype.Text   `db:"plate_number"`
	CommissionBps        pgtype.Int8   `db:"commission_bps"`
	CommissionCentavos   int64         `db:"commission_centavos"`
	DriverPayoutCentavos int64         `db:"driver_payout_centavos"`
}

func (q *Queries) CreateAcceptedRide(ctx context.Context, arg CreateAcceptedRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createAcceptedRide,
		arg.PassengerID,
		arg.DriverID,
		arg.FareCentavos,
		arg.RideType,
		arg.PickupLatitude,
		arg.PickupLongitude,
		arg.PickupName,
		arg.DropoffLatitude,
		arg.DropoffLongitude,
		arg.DropoffName,
		arg.DistanceKm,
		arg.DurationMinutes,
		arg.DriverName,
		arg.VehicleType,
		arg.PlateNumber,
		arg.CommissionBps,
		arg.CommissionCentavos,
		arg.DriverPayoutCentavos,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.Status,
		&i.FareCentavos,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.DriverName,
		&i.VehicleType,
		&i.PlateNumber,
		&i.DriverRating,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PaymentStatus,
		&i.CashReceivedAt,
		&i.CommissionBps,
		&i.CommissionCentavos,
		&i.DriverPayoutCentavos,
	)
	return i, err
}

const createRideSettlement = `-- name: CreateRideSettlement :exec
INSERT INTO ride_settlements (
    ride_id, gross_fare_centavos, commission_bps, commission_centavos,
    driver_payout_centavos, payment_status
)
VALUES ($1, $2, $3, $4, $5, 'unpaid')
`

type CreateRideSettlementParams struct {
	RideID               int32       `db:"ride_id"`
	GrossFareCentavos    int64       `db:"gross_fare_centavos"`
	CommissionBps        pgtype.Int8 `db:"commission_bps"`
	CommissionCentavos   int64       `db:"commission_centavos"`
	DriverPayoutCentavos int64       `db:"driver_payout_centavos"`
}

func (q *Queries) CreateRideSettlement(ctx context.Context, arg CreateRideSettlementParams) error {
	_, err := q.db.Exec(ctx, createRideSettlement,
		arg.RideID,
		arg.GrossFareCentavos,
		arg.CommissionBps,
		arg.CommissionCentavos,
		arg.DriverPayoutCentavos,
	)
	return err
}

const lockPendingBidForAcceptance = `-- name: LockPendingBidForAcceptance :one
SELECT id, ride_id, driver_id, offered_fare_centavos, status
FROM bids
WHERE id = $1
  AND driver_id = $2
  AND status = 'pending'
LIMIT 1
FOR UPDATE
`

type LockPendingBidForAcceptanceParams struct {
	ID       int32 `db:"id"`
	DriverID int32 `db:"driver_id"`
}

func (q *Queries) LockPendingBidForAcceptance(ctx context.Context, arg LockPendingBidForAcceptanceParams) (Bid, error) {
	row := q.db.QueryRow(ctx, lockPendingBidForAcceptance, arg.ID, arg.DriverID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.DriverID,
		&i.OfferedFareCentavos,
		&i.Status,
	)
	return i, err
}

const lockPendingBidOfferForAcceptance = `-- name: LockPendingBidOfferForAcceptance :one
SELECT id, session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status, created_at
FROM bid_offers
WHERE id = $1
  AND session_id = $2
  AND status = 'pending'
LIMIT 1
FOR UPDATE
`

type LockPendingBidOfferForAcceptanceParams struct {
	ID        int32 `db:"id"`
	SessionID int32 `db:"session_id"`
}

func (q *Queries) LockPendingBidOfferForAcceptance(ctx context.Context, arg LockPendingBidOfferForAcceptanceParams) (BidOffer, error) {
	row := q.db.QueryRow(ctx, lockPendingBidOfferForAcceptance, arg.ID, arg.SessionID)
	var i BidOffer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DriverID,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleType,
		&i.ProposedFareCentavos,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const lockRequestedRideForAcceptance = `-- name: LockRequestedRideForAcceptance :one
SELECT id, passenger_id, driver_id, status, fare_centavos, ride_type,
    pickup_latitude, pickup_longitude, pickup_name,
    dropoff_latitude, dropoff_longitude, dropoff_name,
    distance_km, duration_minutes, driver_name, vehicle_type, plate_number,
    driver_rating, created_at, completed_at, payment_status,
    cash_received_at, commission_bps, commission_centavos,
    driver_payout_centavos
FROM rides
WHERE id = $1
  AND status = 'requested'
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockRequestedRideForAcceptance(ctx context.Context, id int32) (Ride, error) {
	row := q.db.QueryRow(ctx, lockRequestedRideForAcceptance, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.Status,
		&i.FareCentavos,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.DriverName,
		&i.VehicleType,
		&i.PlateNumber,
		&i.DriverRating,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PaymentStatus,
		&i.CashReceivedAt,
		&i.CommissionBps,
		&i.CommissionCentavos,
		&i.DriverPayoutCentavos,
	)
	return i, err
}

const markBidAccepted = `-- name: MarkBidAccepted :one
UPDATE bids
SET status = 'accepted'
WHERE id = $1
  AND status = 'pending'
RETURNING id, ride_id, driver_id, offered_fare_centavos, status
`

func (q *Queries) MarkBidAccepted(ctx context.Context, id int32) (Bid, error) {
	row := q.db.QueryRow(ctx, markBidAccepted, id)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.DriverID,
		&i.OfferedFareCentavos,
		&i.Status,
	)
	return i, err
}

const markBidOfferAccepted = `-- name: MarkBidOfferAccepted :one
UPDATE bid_offers
SET status = 'accepted'
WHERE id = $1
  AND status = 'pending'
RETURNING id, session_id, driver_id, driver_name, plate_number, vehicle_type,
    proposed_fare_centavos, status, created_at
`

func (q *Queries) MarkBidOfferAccepted(ctx context.Context, id int32) (BidOffer, error) {
	row := q.db.QueryRow(ctx, markBidOfferAccepted, id)
	var i BidOffer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DriverID,
		&i.DriverName,
		&i.PlateNumber,
		&i.VehicleType,
		&i.ProposedFareCentavos,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markBidSessionAccepted = `-- name: MarkBidSessionAccepted :one
UPDATE bid_sessions
SET status = 'accepted',
    accepted_driver_id = $2
WHERE id = $1
  AND status = 'open'
RETURNING id, passenger_id, ride_type, pickup_latitude, pickup_longitude,
    pickup_name, dropoff_latitude, dropoff_longitude, dropoff_name,
    passenger_note, distance_km, duration_minutes, offered_fare_centavos,
    status, target_driver_id, accepted_driver_id, expires_at, created_at
`

type MarkBidSessionAcceptedParams struct {
	ID               int32       `db:"id"`
	AcceptedDriverID pgtype.Int4 `db:"accepted_driver_id"`
}

func (q *Queries) MarkBidSessionAccepted(ctx context.Context, arg MarkBidSessionAcceptedParams) (BidSession, error) {
	row := q.db.QueryRow(ctx, markBidSessionAccepted, arg.ID, arg.AcceptedDriverID)
	var i BidSession
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.RideType,
		&i.PickupLatitude,
		&i.PickupLongitude,
		&i.PickupName,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.DropoffName,
		&i.PassengerNote,
		&i.DistanceKm,
		&i.DurationMinutes,
		&i.OfferedFareCentavos,
		&i.Status,
		&i.TargetDriverID,
		&i.AcceptedDriverID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const rejectOtherPendingBidOffers = `-- name: RejectOtherPendingBidOffers :exec
UPDATE bid_offers
SET status = 'rejected'
WHERE session_id = $1
  AND status = 'pending'
  AND id <> $2
`

type RejectOtherPendingBidOffersParams struct {
	SessionID int32 `db:"session_id"`
	ID        int32 `db:"id"`
}

func (q *Queries) RejectOtherPendingBidOffers(ctx context.Context, arg RejectOtherPendingBidOffersParams) error {
	_, err := q.db.Exec(ctx, rejectOtherPendingBidOffers, arg.SessionID, arg.ID)
	return err
}
