// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ride_reads.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRideByID = `-- name: GetRideByID :one
SELECT ride.id, ride.passenger_id, ride.driver_id, ride.status, ride.fare_amount, ride.ride_type, ride.pickup_latitude, ride.pickup_longitude, ride.pickup_name, ride.dropoff_latitude, ride.dropoff_longitude, ride.dropoff_name, ride.distance_km, ride.duration_minutes, ride.driver_name, ride.vehicle_type, ride.plate_number, ride.driver_rating, ride.created_at, ride.completed_at, ride.arrived_at, ride.waiting_until, ride.cancelled_by, ride.cancellation_reason, ride.cancellation_responsibility, ride.cancellation_details,
    COALESCE(settlement.payment_status, 'unpaid') AS payment_status,
    COALESCE(settlement.cash_received_amount, 0)::bigint AS cash_received_amount,
    COALESCE(settlement.cash_change_amount, 0)::bigint AS cash_change_amount,
    COALESCE(settlement.cash_outcome, 'unpaid') AS cash_outcome,
    settlement.commission_bps,
    COALESCE(settlement.commission_amount, 0)::bigint AS commission_amount,
    COALESCE(settlement.driver_payout_amount, 0)::bigint AS driver_payout_amount
FROM rides AS ride
LEFT JOIN ride_settlements AS settlement ON settlement.ride_id = ride.id
WHERE ride.id = $1
LIMIT 1
`

type GetRideByIDRow struct {
	Ride               Ride        `db:"ride"`
	PaymentStatus      string      `db:"payment_status"`
	CashReceivedAmount int64       `db:"cash_received_amount"`
	CashChangeAmount   int64       `db:"cash_change_amount"`
	CashOutcome        string      `db:"cash_outcome"`
	CommissionBps      pgtype.Int4 `db:"commission_bps"`
	CommissionAmount   int64       `db:"commission_amount"`
	DriverPayoutAmount int64       `db:"driver_payout_amount"`
}

func (q *Queries) GetRideByID(ctx context.Context, id int32) (GetRideByIDRow, error) {
	row := q.db.QueryRow(ctx, getRideByID, id)
	var i GetRideByIDRow
	err := row.Scan(
		&i.Ride.ID,
		&i.Ride.PassengerID,
		&i.Ride.DriverID,
		&i.Ride.Status,
		&i.Ride.FareAmount,
		&i.Ride.RideType,
		&i.Ride.PickupLatitude,
		&i.Ride.PickupLongitude,
		&i.Ride.PickupName,
		&i.Ride.DropoffLatitude,
		&i.Ride.DropoffLongitude,
		&i.Ride.DropoffName,
		&i.Ride.DistanceKm,
		&i.Ride.DurationMinutes,
		&i.Ride.DriverName,
		&i.Ride.VehicleType,
		&i.Ride.PlateNumber,
		&i.Ride.DriverRating,
		&i.Ride.CreatedAt,
		&i.Ride.CompletedAt,
		&i.Ride.ArrivedAt,
		&i.Ride.WaitingUntil,
		&i.Ride.CancelledBy,
		&i.Ride.CancellationReason,
		&i.Ride.CancellationResponsibility,
		&i.Ride.CancellationDetails,
		&i.PaymentStatus,
		&i.CashReceivedAmount,
		&i.CashChangeAmount,
		&i.CashOutcome,
		&i.CommissionBps,
		&i.CommissionAmount,
		&i.DriverPayoutAmount,
	)
	return i, err
}

const listActiveRidesForDriver = `-- name: ListActiveRidesForDriver :many
SELECT ride.id, ride.passenger_id, ride.driver_id, ride.status, ride.fare_amount, ride.ride_type, ride.pickup_latitude, ride.pickup_longitude, ride.pickup_name, ride.dropoff_latitude, ride.dropoff_longitude, ride.dropoff_name, ride.distance_km, ride.duration_minutes, ride.driver_name, ride.vehicle_type, ride.plate_number, ride.driver_rating, ride.created_at, ride.completed_at, ride.arrived_at, ride.waiting_until, ride.cancelled_by, ride.cancellation_reason, ride.cancellation_responsibility, ride.cancellation_details,
    COALESCE(settlement.payment_status, 'unpaid') AS payment_status,
    COALESCE(settlement.cash_received_amount, 0)::bigint AS cash_received_amount,
    COALESCE(settlement.cash_change_amount, 0)::bigint AS cash_change_amount,
    COALESCE(settlement.cash_outcome, 'unpaid') AS cash_outcome,
    settlement.commission_bps,
    COALESCE(settlement.commission_amount, 0)::bigint AS commission_amount,
    COALESCE(settlement.driver_payout_amount, 0)::bigint AS driver_payout_amount
FROM rides AS ride
LEFT JOIN ride_settlements AS settlement ON settlement.ride_id = ride.id
WHERE ride.driver_id = $1
  AND ride.status IN ('assigned', 'accepted', 'arrived', 'in_transit')
ORDER BY ride.id
`

type ListActiveRidesForDriverRow struct {
	Ride               Ride        `db:"ride"`
	PaymentStatus      string      `db:"payment_status"`
	CashReceivedAmount int64       `db:"cash_received_amount"`
	CashChangeAmount   int64       `db:"cash_change_amount"`
	CashOutcome        string      `db:"cash_outcome"`
	CommissionBps      pgtype.Int4 `db:"commission_bps"`
	CommissionAmount   int64       `db:"commission_amount"`
	DriverPayoutAmount int64       `db:"driver_payout_amount"`
}

func (q *Queries) ListActiveRidesForDriver(ctx context.Context, driverID pgtype.Int4) ([]ListActiveRidesForDriverRow, error) {
	rows, err := q.db.Query(ctx, listActiveRidesForDriver, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRidesForDriverRow{}
	for rows.Next() {
		var i ListActiveRidesForDriverRow
		if err := rows.Scan(
			&i.Ride.ID,
			&i.Ride.PassengerID,
			&i.Ride.DriverID,
			&i.Ride.Status,
			&i.Ride.FareAmount,
			&i.Ride.RideType,
			&i.Ride.PickupLatitude,
			&i.Ride.PickupLongitude,
			&i.Ride.PickupName,
			&i.Ride.DropoffLatitude,
			&i.Ride.DropoffLongitude,
			&i.Ride.DropoffName,
			&i.Ride.DistanceKm,
			&i.Ride.DurationMinutes,
			&i.Ride.DriverName,
			&i.Ride.VehicleType,
			&i.Ride.PlateNumber,
			&i.Ride.DriverRating,
			&i.Ride.CreatedAt,
			&i.Ride.CompletedAt,
			&i.Ride.ArrivedAt,
			&i.Ride.WaitingUntil,
			&i.Ride.CancelledBy,
			&i.Ride.CancellationReason,
			&i.Ride.CancellationResponsibility,
			&i.Ride.CancellationDetails,
			&i.PaymentStatus,
			&i.CashReceivedAmount,
			&i.CashChangeAmount,
			&i.CashOutcome,
			&i.CommissionBps,
			&i.CommissionAmount,
			&i.DriverPayoutAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
