import {
  doublePrecision,
  integer,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

export const bidSessions = pgTable('bid_sessions', {
  id: text('id').primaryKey(),
  passengerId: text('passenger_id').notNull(),
  rideType: text('ride_type').notNull(),
  pickupLatitude: doublePrecision('pickup_latitude').notNull(),
  pickupLongitude: doublePrecision('pickup_longitude').notNull(),
  pickupName: text('pickup_name').notNull(),
  dropoffLatitude: doublePrecision('dropoff_latitude').notNull(),
  dropoffLongitude: doublePrecision('dropoff_longitude').notNull(),
  dropoffName: text('dropoff_name').notNull(),
  distanceKm: doublePrecision('distance_km').notNull(),
  durationMinutes: doublePrecision('duration_minutes').notNull(),
  offeredFare: doublePrecision('offered_fare').notNull(),
  offeredFareCentavos: integer('offered_fare_centavos').notNull(),
  status: text('status').default('open').notNull(),
  acceptedDriverId: text('accepted_driver_id'),
  acceptedOfferId: text('accepted_offer_id'),
  acceptedTripId: text('accepted_trip_id'),
  acceptanceIdempotencyKey: text('acceptance_idempotency_key'),
  assignmentSource: text('assignment_source'),
  assignedByAdminId: text('assigned_by_admin_id'),
  targetDriverId: text('target_driver_id'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'date' }).notNull(),
});
