ALTER TABLE "drivers" ALTER COLUMN "lat" DROP DEFAULT;
ALTER TABLE "drivers" ALTER COLUMN "lng" DROP DEFAULT;
ALTER TABLE "drivers" ALTER COLUMN "lat" DROP NOT NULL;
ALTER TABLE "drivers" ALTER COLUMN "lng" DROP NOT NULL;
