CREATE TABLE IF NOT EXISTS "rides" (
	"id" text PRIMARY KEY NOT NULL,
	"passenger_id" text NOT NULL,
	"passenger_name" text,
	"ride_type" text NOT NULL,
	"pickup_latitude" double precision NOT NULL,
	"pickup_longitude" double precision NOT NULL,
	"pickup_name" text NOT NULL,
	"dropoff_latitude" double precision NOT NULL,
	"dropoff_longitude" double precision NOT NULL,
	"dropoff_name" text NOT NULL,
	"fare" double precision NOT NULL,
	"fare_centavos" integer,
	"commission_rate_basis_points" integer,
	"commission_centavos" integer,
	"credit_reservation_id" text,
	"assignment_source" text DEFAULT 'driver_offer' NOT NULL,
	"assigned_by_admin_id" text,
	"payment_status" text DEFAULT 'cash_pending' NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"driver_id" text,
	"driver_name" text,
	"driver_rating" text,
	"vehicle_type" text,
	"plate_number" text
);
